import type{Composition,Certainty,Freshness}from'../inventory/types.js';
export interface Supplier{id:string;schemaVersion:1;configId:string;displayName:string;fictional:true;archetype:'PRIVATE_FOREST_OWNER'|'SMALL_HARVESTING_CREW'|'REGIONAL_TIMBER_TRADER';status:'ACTIVE'|'INACTIVE'|'BLACKLISTED';locationId:string;channels:string[];suppliedSpeciesIds:string[];suppliedAssortmentIds:string[];paymentExpectationSeconds:number;documentReliabilityBasisPoints:number;freshnessAnswerReliabilityBasisPoints:number;createdTimestamp:number;sourceEventIds:string[]}
export interface SupplierContact{id:string;supplierId:string;displayName:string;role:string;status:'ACTIVE'|'INACTIVE';createdTimestamp:number;sourceEventIds:string[]}
export interface RelationshipState{id:string;supplierId:string;companyId:string;warmthBasisPoints:number;trustBasisPoints:number;favorBalanceBasisPoints:number;lastChangeTimestamp:number;historyEventIds:string[]}
export interface OfferBelief{estimatedVolumeMinMilliM3:number;estimatedVolumeMaxMilliM3:number;freshnessBelief:Freshness|'UNKNOWN';confidenceBasisPoints:number;informationSourceIds:string[]}
export interface OfferTruth{actualVolumeMilliM3:number;actualFreshness:Freshness;composition:Composition}
export interface Offer{id:string;schemaVersion:1;supplierId:string;contactId:string;locationId:string;status:'OPEN'|'ACCEPTED'|'REJECTED'|'EXPIRED'|'FAILED_DOCUMENTS';createdTimestamp:number;expiryTimestamp:number;volumeBasis:'AGREED_VOLUME'|'MILL_MEASURED_VOLUME_PLACEHOLDER';offeredVolumeMilliM3:number;baseRateMinorPerM3:number;currency:'EUR';requiredDocumentTypes:string[];documentSetId:string;belief:OfferBelief;truth:OfferTruth;dealId?:string;lotId?:string;batchId?:string;payableId?:string;commitmentId?:string;acceptedByCompanyId?:string;settlementRecorded?:boolean;sourceEventIds:string[]}
export interface SupplierDocument{id:string;documentSetId:string;documentType:string;issuer:string;reference:string;validFromTimestamp:number;validUntilTimestamp:number;sourceEventIds:string[]}
export interface DocumentSet{id:string;offerId:string;requiredTypes:string[];documentIds:string[];status:'PENDING'|'VALID'|'MISSING_OR_INVALID';missingTypes:string[];validatedTimestamp?:number;sourceEventIds:string[]}
export interface IntelItem{id:string;subjectId:string;sourceId:string;summary:string;confidenceBasisPoints:number;visibility:'PUBLIC'|'PLAYER_VISIBLE'|'PRIVATE_SOURCE';createdTimestamp:number;causalEventIds:string[];kind:'INSPECTION'|'FRESHNESS_ANSWER'|'GOSSIP'|'GENERAL';sourceEventIds:string[]}
export interface SupplierSnapshot{appliedEventIds:string[];suppliers:Supplier[];contacts:SupplierContact[];relationships:RelationshipState[];offers:Offer[];documentSets:DocumentSet[];documents:SupplierDocument[];intelItems:IntelItem[]}
