import{describe,expect,it}from'vitest';import{command,SimulationEngine}from'../src/core/engine.js';import{auctionDetail,auctionList,competitorDirectory,publicAuctionResults}from'../src/auction/read-models.js';import{calculateSaveChecksum,createSave,loadSave}from'../src/persistence/save.js';import{createSnapshot,snapshotChecksum}from'../src/persistence/snapshot.js';const mk=()=>new SimulationEngine({seed:'auction-step-9',configurationBundleVersion:'1',configurationHash:'h',scenarioId:'s',clock:{paused:false}}),go=(e:SimulationEngine,id:string,type:string,p:any={})=>e.execute(command(id,type,e,p));
function world(valuation=6_000,budget=1_000_000,error=500){const e=mk();go(e,'C','CreateCompany',{displayName:'Mežtirgus SIA',reputationBasisPoints:5000});go(e,'CASH','CreateOpeningBalance',{companyId:'COMPANY-000001',amountMinor:budget});go(e,'LOC','CreateLocation',{displayName:'Cēsis roadside',countryCode:'LV',regionCode:'VIDZEME',roles:['ROADSIDE']});go(e,'AI','CreateCompetitor',{displayName:'Ziemeļu Koks',fictional:true,budgetMinor:budget,strategy:'VALUE',privateValuationMinorPerM3:valuation,valuationErrorBasisPoints:error});go(e,'A','CreateAuction',{displayName:'Cēsis prepared birch',auctionType:'PREPARED_ROUNDWOOD',volumeMilliM3:100_000,openingRateMinorPerM3:5_000,incrementMinorPerM3:100,depositBasisPoints:1000,lateWindowSeconds:60,extensionSeconds:120,closeTimestamp:1000,paymentDeadlineSeconds:300,removalDeadlineSeconds:3000,locationId:'LOCATION-000001',composition:{species:[{id:'species.birch',basisPoints:10000}],assortment:[{id:'assortment.sawlogs',basisPoints:10000}],quality:[{id:'quality.birch.b',basisPoints:10000}]},freshness:'FRESH',certainty:'INSPECTED'});return e}function register(e:SimulationEngine){go(e,'RP','RegisterForAuction',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',bidderType:'COMPANY'});go(e,'RA','RegisterForAuction',{auctionId:'AUCTION-000001',bidderId:'COMPETITOR-000001',bidderType:'COMPETITOR'})}
describe('Step 9 auctions and first competitor',()=>{
it('creates deterministic fictional competitor and auction IDs',()=>{const e=world();expect(e.auctions.competitor('COMPETITOR-000001')).toMatchObject({fictional:true,displayName:'Ziemeļu Koks'});expect(e.auctions.auction('AUCTION-000001')).toMatchObject({status:'OPEN',auctionType:'PREPARED_ROUNDWOOD'})});
it('rejects invalid competitor and auction atomically',()=>{const e=mk();for(const[type,p]of[['CreateCompetitor',{}],['CreateAuction',{}]]as any){const before=e.auditFingerprint();expect(go(e,'BAD',type,p).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)}});
it('registration reserves an exact player deposit commitment without changing cash',()=>{const e=world(),cash=e.finance.balanceByCode('COMPANY-000001','OPERATING_CASH');go(e,'R','RegisterForAuction',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',bidderType:'COMPANY'});expect(e.auctions.registration('AUCTION-000001','COMPANY-000001')).toMatchObject({depositMinor:50_000,depositCommitmentId:'COMMITMENT-000002'});expect(e.finance.commitment('COMMITMENT-000002')).toMatchObject({amountMinor:50_000,status:'ACTIVE',purpose:'AUCTION_DEPOSIT'});expect(e.finance.balanceByCode('COMPANY-000001','OPERATING_CASH')).toBe(cash)});
it('competitor registration reserves hidden budget only',()=>{const e=world();go(e,'R','RegisterForAuction',{auctionId:'AUCTION-000001',bidderId:'COMPETITOR-000001',bidderType:'COMPETITOR'});expect(e.auctions.competitor('COMPETITOR-000001')!.reservedMinor).toBe(50_000);expect(e.finance.snapshot().commitments).toHaveLength(0)});
it('registration rejects insufficient company or competitor funds',()=>{const e=world(6000,49_999);const before=e.auditFingerprint();expect(go(e,'R','RegisterForAuction',{auctionId:'AUCTION-000001',bidderId:'COMPETITOR-000001',bidderType:'COMPETITOR'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('forbids uncapped player bids',()=>{const e=world();register(e);const before=e.auditFingerprint();expect(go(e,'B','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('enforces opening rate and fixed increment',()=>{const e=world();register(e);expect(go(e,'B1','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500}).accepted).toBe(true);const before=e.auditFingerprint();expect(go(e,'B2','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_050,proxyMaximumMinorPerM3:5_500}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(go(e,'B3','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_100,proxyMaximumMinorPerM3:5_500}).accepted).toBe(true)});
it('never permits bid rate above proxy cap',()=>{const e=world();register(e);expect(go(e,'B','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_100,proxyMaximumMinorPerM3:5_000}).accepted).toBe(false)});
it('company cannot bid beyond cash availability',()=>{const e=world();register(e);const before=e.auditFingerprint();expect(go(e,'B','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:20_000,proxyMaximumMinorPerM3:20_000}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('competitor cannot exceed hidden budget or valuation cap',()=>{const e=world(20_000,509_999,0);register(e);go(e,'P','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_000});const result=go(e,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});expect(result.accepted).toBe(false);expect(e.auctions.snapshot().bids).toHaveLength(1)});
it('competitor evaluation uses stored deterministic named RNG material',()=>{const a=world(),b=world();register(a);register(b);go(a,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});go(b,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});const x=a.eventLog.all().find(x=>x.eventType==='CompetitorBidEvaluated')!,y=b.eventLog.all().find(x=>x.eventType==='CompetitorBidEvaluated')!;expect(x.payload).toEqual(y.payload);expect(x.payload.useAuctionRng).toBe(true)});
it('late valid bid extends close exactly',()=>{const e=world();register(e);e.advanceUntil(950);go(e,'B','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500});expect(e.auctions.auction('AUCTION-000001')!.closeTimestamp).toBe(1120);expect(e.queue.snapshot().some(x=>x.eventType==='AuctionCloseDue'&&x.scheduledGameTime===1120)).toBe(true)});
it('old close is stale after extension and new close is exact',()=>{const e=world();register(e);e.advanceUntil(950);go(e,'B','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500});e.advanceUntil(1000);expect(e.auctions.auction('AUCTION-000001')!.status).toBe('OPEN');e.advanceUntil(1119);expect(e.auctions.auction('AUCTION-000001')!.status).toBe('OPEN');e.advanceUntil(1120);expect(e.auctions.auction('AUCTION-000001')!.status).toBe('CLOSED')});
it('close deterministically selects highest bid and publishes identities',()=>{const e=world(6_000,1_000_000,0);register(e);go(e,'P','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500});go(e,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});e.advanceUntil(1000);expect(publicAuctionResults(e)[0]).toMatchObject({winnerId:'COMPETITOR-000001',winningRateMinorPerM3:5_100,publicBidderIds:['COMPANY-000001','COMPETITOR-000001']})});
it('losing company deposit is released at close',()=>{const e=world(6_000,1_000_000,0);register(e);go(e,'P','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500});go(e,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});e.advanceUntil(1000);expect(e.finance.commitment('COMMITMENT-000002')!.status).toBe('RELEASED');expect(e.auctions.registration('AUCTION-000001','COMPANY-000001')!.status).toBe('LOST_RELEASED')});
it('winning company creates one exact finance commitment',()=>{const e=world(4_900,1_000_000,0);register(e);go(e,'P','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:5_000,proxyMaximumMinorPerM3:5_500});go(e,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});e.advanceUntil(1000);expect(e.auctions.auction('AUCTION-000001')).toMatchObject({winnerId:'COMPANY-000001',winningTotalMinor:500_000});expect(e.finance.commitment('COMMITMENT-000001')).toMatchObject({amountMinor:500_000,purpose:'AUCTION_WIN',status:'ACTIVE'});expect(e.finance.snapshot().commitments.filter(x=>x.purpose==='AUCTION_WIN')).toHaveLength(1)});
it('close with no bids releases all player deposits and has no winner',()=>{const e=world();register(e);e.advanceUntil(1000);expect(e.auctions.auction('AUCTION-000001')).toMatchObject({status:'CLOSED',resultPublished:true});expect(e.auctions.auction('AUCTION-000001')!.winnerId).toBeUndefined();expect(e.finance.commitment('COMMITMENT-000002')!.status).toBe('RELEASED')});
it('ordinary read models hide competitor strategy, valuation, and budget',()=>{const e=world(),view:any=competitorDirectory(e)[0];expect(view.displayName).toBe('Ziemeļu Koks');expect(view.strategy).toBeUndefined();expect(view.budgetMinor).toBeUndefined();expect(view.privateValuationMinorPerM3).toBeUndefined();expect(view.valuationErrorBasisPoints).toBeUndefined()});
it('read models are defensive and RNG-free',()=>{const e=world(),rng=e.rng.snapshot(),list:any=auctionList(e),detail:any=auctionDetail(e,'AUCTION-000001');list[0].displayName='bad';detail.auction.status='CLOSED';expect(auctionList(e)[0]!.displayName).toBe('Cēsis prepared birch');expect(e.auctions.auction('AUCTION-000001')!.status).toBe('OPEN');expect(e.rng.snapshot()).toEqual(rng)});
it('save/load/replay preserves bids, close, counters, RNG, and checksum',()=>{const e=world(),snap=createSnapshot(e);register(e);go(e,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});e.advanceUntil(1000);const loaded=loadSave(createSave(e,snap));expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(loaded.auctions.snapshot()).toEqual(e.auctions.snapshot());expect(loaded.ids.next('auction','AUCTION')).toBe('AUCTION-000002')});
it('migrates version 7 without losing Steps 1–8',()=>{const legacy=world(),save:any=createSave(legacy,createSnapshot(legacy));delete save.snapshot.state.auctions;save.snapshot.snapshotSchemaVersion=7;const{snapshotChecksum:_,...bare}=save.snapshot;save.snapshot.snapshotChecksum=snapshotChecksum(bare);save.saveSchemaVersion=7;save.coreVersion='0.8.0';const{saveChecksum:__,...saveBare}=save;save.saveChecksum=calculateSaveChecksum(saveBare);const loaded=loadSave(save);expect(loaded.transport.snapshot()).toEqual(legacy.transport.snapshot());expect(loaded.inventory.snapshot()).toEqual(legacy.inventory.snapshot());expect(loaded.auctions.snapshot()).toEqual({appliedEventIds:[],competitors:[],auctions:[],registrations:[],bids:[],results:[]})});
it('same seed and sequence produce identical checksums',()=>{const a=world(),b=world();register(a);register(b);go(a,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});go(b,'AI','RunCompetitorBid',{auctionId:'AUCTION-000001',competitorId:'COMPETITOR-000001'});expect(a.stateChecksum()).toBe(b.stateChecksum());expect(a.eventLogChecksum()).toBe(b.eventLogChecksum())});
it.each(Array.from({length:12},(_,i)=>i))('invalid bid path %i is atomic and RNG-neutral',i=>{const e=world();register(e);const before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'BAD','PlaceAuctionBid',{auctionId:'AUCTION-000001',bidderId:'COMPANY-000001',rateMinorPerM3:i%2?0:1.5,proxyMaximumMinorPerM3:5_000}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
it('contains no Step 14 UI state',()=>{const s:any=world().authoritativeState();expect(s.markets).toBeDefined();expect(s.ui).toBeUndefined()});
});
