import{describe,expect,it}from'vitest';import{command,SimulationEngine}from'../src/core/engine.js';import{calculateSaveChecksum,createSave,loadSave}from'../src/persistence/save.js';import{createSnapshot,snapshotChecksum}from'../src/persistence/snapshot.js';import{buyerCompatibility,buyerDemandView,buyerDirectory,calculatedPriceCards,measurementView}from'../src/buyer/read-models.js';import{financeHeader}from'../src/finance/read-models.js';
const good={species:[{id:'species.birch',basisPoints:10000}],assortment:[{id:'assortment.veneer_logs',basisPoints:10000}],quality:[{id:'quality.birch.a',basisPoints:1000},{id:'quality.birch.b',basisPoints:9000}]},mixed={...good,quality:[{id:'quality.birch.a',basisPoints:500},{id:'quality.birch.b',basisPoints:5000},{id:'quality.birch.tara_c',basisPoints:4000},{id:'quality.birch.brakis',basisPoints:500}]},bad={species:[{id:'species.spruce',basisPoints:10000}],assortment:[{id:'assortment.sawlogs',basisPoints:10000}],quality:[{id:'quality.birch.b',basisPoints:10000}]};
const mk=()=>new SimulationEngine({seed:'buyer-step-6',configurationBundleVersion:'1',configurationHash:'h',scenarioId:'s',clock:{paused:false}}),go=(e:SimulationEngine,n:string,t:string,p:any={})=>e.execute(command(n,t,e,p));
function world(composition:any=good,terms=3600,stock=10_000,target=100_000,capacity=200_000,instantDiscount=500){const e=mk();go(e,'SELLER','CreateCompany',{displayName:'Mežtirgus SIA',reputationBasisPoints:5000});go(e,'MILLCO','CreateCompany',{displayName:'Fictional Mill Operator',companyType:'DEMONSTRATION_AI',reputationBasisPoints:5000});go(e,'A','CreateLocation',{displayName:'Cēsis yard',countryCode:'LV',regionCode:'VIDZEME',roles:['YARD']});go(e,'B','CreateLocation',{displayName:'Fictional buyer gate',countryCode:'LV',regionCode:'VIDZEME',roles:['BUYER']});go(e,'AB','CreateRouteEdge',{fromLocationId:'LOCATION-000001',toLocationId:'LOCATION-000002',accessClass:'PAVED',distanceMetres:1000,travelSeconds:60});go(e,'D','CreateDeal',{companyId:'COMPANY-000001',counterpartyId:'supplier.demo',currency:'EUR',expectedVolumeMilliM3:30_000,description:'buyer test',financeSourceIds:[]});go(e,'DA','ActivateDeal',{dealId:'DEAL-000001'});go(e,'LOT','CreateLot',{dealId:'DEAL-000001',ownerCompanyId:'COMPANY-000001',custodyActorId:'custodian.demo',locationId:'LOCATION-000001',originalVolumeMilliM3:30_000,composition,freshness:'FRESH',certainty:'ESTIMATED'});go(e,'BAT','CreateInitialBatch',{lotId:'LOT-000001',volumeMilliM3:30_000,composition});go(e,'LOAD','CreateLoad',{ownerCompanyId:'COMPANY-000001',custodyActorId:'custodian.demo',originLocationId:'LOCATION-000001',destinationLocationId:'LOCATION-000002'});go(e,'ALLOC','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000001',volumeMilliM3:30_000});go(e,'MOVE','MoveLoad',{loadId:'LOAD-000001',toLocationId:'LOCATION-000002'});go(e,'UNLOAD','UnloadLoad',{loadId:'LOAD-000001'});go(e,'BUYER','CreateBuyer',{configId:'buyer.daugava_veneer',displayName:'Daugava Veneer Works',fictional:true,buyerType:'BIRCH_VENEER',companyId:'COMPANY-000002',locationId:'LOCATION-000002',compatibility:[{speciesId:'species.birch',assortmentId:'assortment.veneer_logs',accepted:true},{speciesId:'species.spruce',assortmentId:'assortment.sawlogs',accepted:false}],capacityMilliM3:capacity,stockMilliM3:stock,targetStockMilliM3:target,consumptionMilliM3PerDay:20_000,paymentTermsSeconds:terms,instantPaymentDiscountMinorPerM3:instantDiscount,measurementBiasMinBasisPoints:10,measurementBiasMaxBasisPoints:30,strictnessBasisPoints:5000,fictionalBehaviorNote:'Fictional conservative measurement distribution.'});return e}
function card(e:SimulationEngine,option='STANDARD'){return go(e,'CARD','PublishBuyerPriceCard',{buyerId:'BUYER-000001',speciesId:'species.birch',assortmentId:'assortment.veneer_logs',baseRateMinorPerM3:10_000,paymentOption:option})}
describe('Step 6 buyers, compatibility, demand, price cards, and measurement',()=>{
 it('creates a valid fictional buyer with deterministic ID',()=>{const e=world();expect(e.buyers.buyer('BUYER-000001')).toMatchObject({fictional:true,buyerType:'BIRCH_VENEER',stockMilliM3:10_000})});
 it('invalid buyer creation is deeply atomic',()=>{const e=mk(),before=e.auditFingerprint();expect(go(e,'BAD','CreateBuyer',{}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('publishes only compatible cards with inspectable integer causes',()=>{const e=world();expect(card(e).accepted).toBe(true);expect(calculatedPriceCards(e,'BUYER-000001')[0]!.breakdown).toMatchObject({baseRateMinorPerM3:10_000,hungerBasisPoints:9000});expect(go(e,'BAD','PublishBuyerPriceCard',{buyerId:'BUYER-000001',speciesId:'species.spruce',assortmentId:'assortment.sawlogs',baseRateMinorPerM3:100}).accepted).toBe(false)});
 it('same state produces the same calculated rate',()=>{const e=world();card(e);const first=calculatedPriceCards(e,'BUYER-000001')[0]!.breakdown.finalRateMinorPerM3;go(e,'CARD2','PublishBuyerPriceCard',{buyerId:'BUYER-000001',speciesId:'species.birch',assortmentId:'assortment.veneer_logs',baseRateMinorPerM3:10_000});expect(calculatedPriceCards(e,'BUYER-000001')[1]!.breakdown.finalRateMinorPerM3).toBe(first)});
 it('causal demand and hunger changes alter later cards',()=>{const e=world();card(e);const first=calculatedPriceCards(e,'BUYER-000001')[0]!.breakdown.finalRateMinorPerM3;go(e,'DEMAND','SetBuyerDemand',{buyerId:'BUYER-000001',targetStockMilliM3:20_000,consumptionMilliM3PerDay:20_000});go(e,'CARD2','PublishBuyerPriceCard',{buyerId:'BUYER-000001',speciesId:'species.birch',assortmentId:'assortment.veneer_logs',baseRateMinorPerM3:10_000});expect(calculatedPriceCards(e,'BUYER-000001')[1]!.breakdown.finalRateMinorPerM3).not.toBe(first)});
 it('stock consumption releases capacity and increases hunger causally',()=>{const e=world(good,3600,50_000),before=buyerDemandView(e,'BUYER-000001')!;go(e,'CONSUME','ConsumeBuyerStock',{buyerId:'BUYER-000001',volumeMilliM3:10_000});const after=buyerDemandView(e,'BUYER-000001')!;expect(after.availableCapacityMilliM3).toBe(before.availableCapacityMilliM3+10_000);expect(after.hungerBasisPoints).toBeGreaterThan(before.hungerBasisPoints)});
 it('incompatible delivered load is refused and creates no revenue',()=>{const e=world(bad);card(e);const before=e.finance.snapshot();expect(go(e,'SUBMIT','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'}).accepted).toBe(true);expect(e.buyers.measurement('MEASUREMENT-000001')).toMatchObject({gateDecision:'REFUSE',status:'REFUSED'});expect(e.finance.snapshot()).toEqual(before)});
 it('compatible measurement is deterministic and conserves measured grades',()=>{const a=world(),b=world();card(a);card(b);go(a,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});go(b,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const x=a.buyers.measurement('MEASUREMENT-000001')!,y=b.buyers.measurement('MEASUREMENT-000001')!;expect(x).toEqual(y);expect(x.gradeAllocations.reduce((n,g)=>n+g.volumeMilliM3,0)).toBe(x.measuredVolumeMilliM3);expect(x.acceptedVolumeMilliM3+x.rejectedVolumeMilliM3).toBe(x.measuredVolumeMilliM3)});
 it('mixed quality reprices and rejects only explicit brāķis volume',()=>{const e=world(mixed);card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const m=e.buyers.measurement('MEASUREMENT-000001')!;expect(m.gateDecision).toBe('REPRICE');expect(m.rejectedVolumeMilliM3).toBeGreaterThan(0);expect(m.receivableId).toBeTruthy()});
 it('receivable principal uses accepted measured volume rather than dispatched volume',()=>{const e=world();card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const m=e.buyers.measurement('MEASUREMENT-000001')!,r=e.finance.receivable(m.receivableId!)!;expect(r.principalMinor).toBe(Number(BigInt(m.acceptedVolumeMilliM3)*BigInt(m.rateMinorPerM3)/1000n));expect(m.measuredVolumeMilliM3).toBeLessThan(m.dispatchedVolumeMilliM3)});
 it('partial rejection creates no receivable value for rejected volume',()=>{const e=world(mixed);card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const m=e.buyers.measurement('MEASUREMENT-000001')!,full=Number(BigInt(m.measuredVolumeMilliM3)*BigInt(m.rateMinorPerM3)/1000n);expect(m.principalMinor).toBeLessThan(full)});
 it('dispatched and unloaded volume alone creates no revenue',()=>{const e=world();expect(e.finance.snapshot().receivables).toHaveLength(0);expect(e.finance.balanceByCode('COMPANY-000001','REVENUE')).toBe(0)});
 it('delayed payment creates cash and settles the measured receivable exactly',()=>{const e=world();card(e);const cash=financeHeader(e,'COMPANY-000001').cashBalanceMinor;go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const principal=e.finance.snapshot().receivables[0]!.principalMinor;e.advanceUntil(3599);expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(cash);e.advanceUntil(3600);expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(cash+principal);expect(e.finance.snapshot().receivables[0]!.status).toBe('PAID')});
 it('instant option applies configured discount and pays immediately',()=>{const e=world();card(e,'INSTANT');go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});expect(e.finance.snapshot().receivables[0]!.status).toBe('PAID');expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(e.finance.snapshot().receivables[0]!.principalMinor)});
 it('manual early payment makes the scheduled buyer payment stale and safe',()=>{const e=world();card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const r=e.finance.snapshot().receivables[0]!;go(e,'EARLY','RecordReceivablePayment',{receivableId:r.id,amountMinor:r.principalMinor});const cash=financeHeader(e,'COMPANY-000001').cashBalanceMinor;e.advanceUntil(3600);expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(cash);expect(e.finance.receivable(r.id)!.amountPaidMinor).toBe(r.principalMinor)});
 it('duplicate payment is prevented by existing finance validation',()=>{const e=world();card(e,'INSTANT');go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const r=e.finance.snapshot().receivables[0]!;expect(go(e,'DUP','RecordReceivablePayment',{receivableId:r.id,amountMinor:1}).accepted).toBe(false)});
 it('buyer capacity is conserved and over-capacity submission is atomic',()=>{const e=world(good,3600,10_000,100_000,35_000);card(e);const before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
 it('a delivered Load cannot be measured or invoiced twice',()=>{const e=world();card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const before=e.auditFingerprint();expect(go(e,'S2','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.finance.snapshot().receivables).toHaveLength(1)});
 it('supports one explicit dispute-choice branch',()=>{const e=world();card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});go(e,'DISPUTE','ChooseMeasurementDispute',{measurementId:'MEASUREMENT-000001',choice:'CHALLENGE'});expect(e.buyers.measurement('MEASUREMENT-000001')).toMatchObject({status:'DISPUTED',disputeChoice:'CHALLENGE'})});
 it('save/load/replay preserves measurement RNG, payment schedule and checksums',()=>{const e=world();card(e);const snap=createSnapshot(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});const loaded=loadSave(createSave(e,snap));expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(loaded.buyers.snapshot()).toEqual(e.buyers.snapshot());loaded.advanceUntil(3600);e.advanceUntil(3600);expect(loaded.stateChecksum()).toBe(e.stateChecksum())});
 it('migrates a version-4 fixture without losing Step 1–5 state',()=>{const legacy=world();const save:any=createSave(legacy,createSnapshot(legacy));delete save.snapshot.state.buyers;save.snapshot.snapshotSchemaVersion=4;const{snapshotChecksum:oldSnapshotChecksum,...snapshotBare}=save.snapshot;save.snapshot.snapshotChecksum=snapshotChecksum(snapshotBare);save.saveSchemaVersion=4;save.coreVersion='0.5.0';const{saveChecksum:oldSaveChecksum,...saveBare}=save;save.saveChecksum=calculateSaveChecksum(saveBare);const loaded=loadSave(save);expect(loaded.finance.snapshot()).toEqual(legacy.finance.snapshot());expect(loaded.inventory.snapshot()).toEqual(legacy.inventory.snapshot());expect(loaded.buyers.snapshot()).toEqual({appliedEventIds:[],buyers:[],priceCards:[],measurements:[]})});
 it('read models are defensive, RNG-free, and never expose hidden truth',()=>{const e=world(),rng=e.rng.snapshot(),directory:any=buyerDirectory(e);expect(directory[0].truth).toBeUndefined();directory[0].displayName='bad';buyerCompatibility(e,'BUYER-000001');buyerDemandView(e,'BUYER-000001');expect(buyerDirectory(e)[0]!.displayName).not.toBe('bad');expect(e.rng.snapshot()).toEqual(rng)});
 it('measurement public view omits hidden buyer traits',()=>{const e=world();card(e);go(e,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});expect((measurementView(e,'MEASUREMENT-000001')as any).truth).toBeUndefined()});
 it('same seed and commands produce deterministic authoritative and event checksums',()=>{const a=world(),b=world();card(a);card(b);go(a,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});go(b,'S','SubmitLoadToBuyer',{buyerId:'BUYER-000001',loadId:'LOAD-000001',priceCardId:'PRICECARD-000001'});expect(a.stateChecksum()).toBe(b.stateChecksum());expect(a.eventLogChecksum()).toBe(b.eventLogChecksum())});
 it.each(Array.from({length:15},(_,i)=>i))('rejection path %i is atomic and RNG-neutral',i=>{const e=world(),before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'BAD','PublishBuyerPriceCard',{buyerId:'BUYER-000001',speciesId:'species.birch',assortmentId:'assortment.veneer_logs',baseRateMinorPerM3:i%2?0:1.5}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
 it('contains no Step 8 logistics, dispatch, vehicle, driver, or load-plan state',()=>{const state:any=world().authoritativeState();expect(state.logistics).toBeUndefined();expect(state.dispatch).toBeUndefined();expect(state.vehicles).toBeUndefined();expect(state.drivers).toBeUndefined();expect(state.loadPlans).toBeUndefined()});
});
