import{describe,expect,it}from'vitest';import{command,SimulationEngine}from'../src/core/engine.js';import{calculateSaveChecksum,createSave,loadSave,replayEventsFromSnapshot}from'../src/persistence/save.js';import{createSnapshot,snapshotChecksum}from'../src/persistence/snapshot.js';import{batchAncestry,costReconciliation,dealTree,inventoryGrid,inventoryReconciliation,loadComposition}from'../src/inventory/read-models.js';import{addVolume,allocateInteger,subtractVolume,validateComposition,weightedComposition}from'../src/inventory/value-objects.js';
const comp={species:[{id:'species.birch',basisPoints:7000},{id:'species.spruce',basisPoints:3000}],assortment:[{id:'assortment.veneer_logs',basisPoints:5000},{id:'assortment.pulpwood',basisPoints:5000}],quality:[{id:'quality.birch.a',basisPoints:500},{id:'quality.birch.b',basisPoints:5000},{id:'quality.birch.tara_c',basisPoints:4000},{id:'quality.birch.brakis',basisPoints:500}]};
const mk=()=>new SimulationEngine({seed:'inventory',configurationBundleVersion:'1',configurationHash:'h',scenarioId:'s',clock:{paused:false}});const go=(e:SimulationEngine,n:string,t:string,p:any={})=>e.execute(command(n,t,e,p));
function base(volume=100_000){const e=mk();go(e,'C','CreateCompany',{displayName:'Mežtirgus SIA',reputationBasisPoints:5000});const companyId=e.finance.snapshot().companies[0]!.id;go(e,'L1','CreateLocation',{displayName:'Cēsis',countryCode:'LV',regionCode:'VIDZEME',roles:['YARD']});go(e,'L2','CreateLocation',{displayName:'Rīga',countryCode:'LV',regionCode:'RIGA',roles:['REGIONAL_NODE']});const[a,b]=e.routing.snapshot().locations.map(x=>x.id);go(e,'R1','CreateRouteEdge',{fromLocationId:a,toLocationId:b,accessClass:'PAVED',accessState:'OPEN',distanceMetres:90_000,travelSeconds:5400});go(e,'R2','CreateRouteEdge',{fromLocationId:b,toLocationId:a,accessClass:'PAVED',accessState:'OPEN',distanceMetres:90_000,travelSeconds:5400});go(e,'D','CreateDeal',{companyId,counterpartyId:'counterparty.demo',currency:'EUR',expectedVolumeMilliM3:volume,description:'Diagnostic timber ancestry',financeSourceIds:[]});go(e,'DA','ActivateDeal',{dealId:'DEAL-000001'});go(e,'LOT','CreateLot',{dealId:'DEAL-000001',ownerCompanyId:companyId,custodyActorId:'custodian.demo',locationId:a,originalVolumeMilliM3:volume,composition:comp,freshness:'FRESH',certainty:'ESTIMATED'});go(e,'B','CreateInitialBatch',{lotId:'LOT-000001',volumeMilliM3:volume,composition:comp});return{e,companyId,a:a!,b:b!}}
function splitFixture(){const x=base();go(x.e,'COST','AddCostLayer',{attachedToType:'BATCH',attachedToId:'BATCH-000001',sourceObjectId:'deal.demo',category:'ACQUISITION',currency:'EUR',totalMinor:25_001,attributableVolumeMilliM3:100_000,allocationMethod:'VOLUME_PROPORTIONAL',provenanceReference:'prov.tunable'});go(x.e,'S','SplitBatch',{batchId:'BATCH-000001',childVolumesMilliM3:[33_333,33_333,33_334]});return x}
describe('Step 5 deal-lot-batch-load and inventory',()=>{
 it('creates deterministic namespaced entity IDs and a reconciled spine',()=>{const{e}=base();expect(e.inventory.snapshot()).toMatchObject({deals:[{id:'DEAL-000001'}],lots:[{id:'LOT-000001'}],batches:[{id:'BATCH-000001'}]});expect(inventoryReconciliation(e).reconciles).toBe(true)});
 it('keeps rejected Deal and Lot commands deeply atomic',()=>{const e=mk();for(const[t,p]of ([['CreateDeal',{}],['CreateLot',{dealId:'NO'}]] as Array<[string,any]>)){const before=e.auditFingerprint();expect(go(e,'BAD',t,p).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)}});
 it('requires existing deals, companies, locations and configured IDs',()=>{const{e}=base();const before=e.auditFingerprint();expect(go(e,'BAD','CreateInitialBatch',{lotId:'LOT-000001',volumeMilliM3:1,composition:{...comp,species:[{id:'species.invalid',basisPoints:10000}]}}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('validates composition scale and both embedded tara and brāķis',()=>{expect(validateComposition(comp,1).quality.map(x=>x.id)).toContain('quality.birch.tara_c');expect(validateComposition(comp,1).quality.map(x=>x.id)).toContain('quality.birch.brakis');expect(()=>validateComposition({...comp,quality:[{id:'quality.birch.a',basisPoints:9999}]},1)).toThrow('10000')});
 it('checks exact volume arithmetic and overflow',()=>{expect(addVolume(1,2)).toBe(3);expect(subtractVolume(2,1)).toBe(1);expect(()=>subtractVolume(1,2)).toThrow('underflow');expect(()=>addVolume(Number.MAX_SAFE_INTEGER,1)).toThrow('overflow')});
 it('reservation changes availability but never physical volume and releases once',()=>{const{e,companyId}=base();go(e,'RES','CreateInventoryReservation',{companyId,batchId:'BATCH-000001',purpose:'load',sourceObjectId:'x',volumeMilliM3:10_000});expect(inventoryReconciliation(e)).toMatchObject({currentPhysicalVolumeMilliM3:100_000,reservedVolumeMilliM3:10_000,availableVolumeMilliM3:90_000});go(e,'REL','ReleaseInventoryReservation',{reservationId:'RESERVATION-000001'});expect(inventoryReconciliation(e).availableVolumeMilliM3).toBe(100_000);const before=e.auditFingerprint();expect(go(e,'REL2','ReleaseInventoryReservation',{reservationId:'RESERVATION-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('expires reservations at the exact scheduled second and stale expiry is harmless',()=>{const{e,companyId}=base();go(e,'RES','CreateInventoryReservation',{companyId,batchId:'BATCH-000001',purpose:'hold',sourceObjectId:'x',volumeMilliM3:1_000,expectedReleaseTimestamp:1800});e.advanceUntil(1799);expect(e.inventory.reservation('RESERVATION-000001')!.status).toBe('ACTIVE');e.advanceUntil(1800);expect(e.inventory.reservation('RESERVATION-000001')!.status).toBe('EXPIRED');e.advanceUntil(3600);expect(e.inventory.reservation('RESERVATION-000001')!.status).toBe('EXPIRED')});
 it('full explicit-child split conserves volume, composition, cost and ancestry',()=>{const{e}=splitFixture(),s=e.inventory.snapshot(),children=s.batches.slice(1);expect(children.reduce((n,b)=>n+b.currentVolumeMilliM3,0)).toBe(100_000);expect(children.every(b=>JSON.stringify(b.composition)===JSON.stringify(comp))).toBe(true);expect(s.costLayers.filter(x=>x.status==='ACTIVE').reduce((n,x)=>n+x.totalMinor,0)).toBe(25_001);expect(batchAncestry(e,'BATCH-000002')!.parents[0].batch.id).toBe('BATCH-000001')});
 it('separated tara child path conserves physical volume',()=>{const{e}=base();go(e,'S','SplitBatch',{batchId:'BATCH-000001',childVolumesMilliM3:[40_000,60_000]});expect(inventoryReconciliation(e).currentPhysicalVolumeMilliM3).toBe(100_000)});
 it('duplicate split and zero child reject atomically',()=>{const{e}=splitFixture();for(const p of[{batchId:'BATCH-000001',childVolumesMilliM3:[50_000,50_000]},{batchId:'BATCH-000002',childVolumesMilliM3:[0,33_333]}]){const before=e.auditFingerprint();expect(go(e,'BAD','SplitBatch',p).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)}});
 it('compatible merge conserves volume, weighted composition and costs',()=>{const{e}=splitFixture();expect(go(e,'M','MergeBatches',{batchIds:['BATCH-000002','BATCH-000003','BATCH-000004']}).accepted).toBe(true);const b=e.inventory.batch('BATCH-000005')!;expect(b.currentVolumeMilliM3).toBe(100_000);expect(b.composition.quality).toEqual(comp.quality);expect(e.inventory.snapshot().costLayers.filter(x=>x.attachedToId===b.id&&x.status==='ACTIVE').reduce((n,x)=>n+x.totalMinor,0)).toBe(25_001)});
 it('rejects self, repeated, reserved and incompatible-location merges atomically',()=>{const{e,companyId,b}=splitFixture();go(e,'RES','CreateInventoryReservation',{companyId,batchId:'BATCH-000002',purpose:'x',sourceObjectId:'x',volumeMilliM3:1});for(const ids of[['BATCH-000002','BATCH-000002'],['BATCH-000002','BATCH-000003']]){const before=e.auditFingerprint();expect(go(e,'BAD','MergeBatches',{batchIds:ids}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)}go(e,'REL','ReleaseInventoryReservation',{reservationId:'RESERVATION-000001'});go(e,'MOVE','MoveBatch',{batchId:'BATCH-000003',toLocationId:b});expect(go(e,'BAD3','MergeBatches',{batchIds:['BATCH-000002','BATCH-000003']}).accepted).toBe(false)});
 it('allocates one batch across loads without double allocation',()=>{const{e,companyId,a,b}=base();for(let i=1;i<=2;i++)go(e,'LOAD'+i,'CreateLoad',{ownerCompanyId:companyId,custodyActorId:'custodian.demo',originLocationId:a,destinationLocationId:b});go(e,'A1','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000001',volumeMilliM3:60_000});go(e,'A2','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000002',volumeMilliM3:40_000});expect(inventoryReconciliation(e)).toMatchObject({allocatedVolumeMilliM3:100_000,availableVolumeMilliM3:0,reconciles:true});const before=e.auditFingerprint();expect(go(e,'A3','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000002',volumeMilliM3:1}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('consumes an exact reservation into one allocation',()=>{const{e,companyId,a}=base();go(e,'L','CreateLoad',{ownerCompanyId:companyId,custodyActorId:'custodian.demo',originLocationId:a});go(e,'R','CreateInventoryReservation',{companyId,batchId:'BATCH-000001',purpose:'load',sourceObjectId:'LOAD-000001',volumeMilliM3:12_345});go(e,'A','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000001',volumeMilliM3:12_345,reservationId:'RESERVATION-000001'});expect(e.inventory.reservation('RESERVATION-000001')).toMatchObject({status:'CONSUMED',allocationId:'ALLOCATION-000001'})});
 it('releasing allocation restores availability and cannot happen twice',()=>{const{e,companyId,a}=base();go(e,'L','CreateLoad',{ownerCompanyId:companyId,custodyActorId:'custodian.demo',originLocationId:a});go(e,'A','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000001',volumeMilliM3:10_000});go(e,'R','ReleaseLoadAllocation',{allocationId:'ALLOCATION-000001'});expect(inventoryReconciliation(e).availableVolumeMilliM3).toBe(100_000);expect(go(e,'R2','ReleaseLoadAllocation',{allocationId:'ALLOCATION-000001'}).accepted).toBe(false)});
 it('derives exact weighted load composition from multiple batches',()=>{const{e,companyId,a}=splitFixture();go(e,'L','CreateLoad',{ownerCompanyId:companyId,custodyActorId:'custodian.demo',originLocationId:a});go(e,'A1','AllocateBatchToLoad',{batchId:'BATCH-000002',loadId:'LOAD-000001',volumeMilliM3:10_000});go(e,'A2','AllocateBatchToLoad',{batchId:'BATCH-000003',loadId:'LOAD-000001',volumeMilliM3:20_000});expect(loadComposition(e,'LOAD-000001')).toMatchObject({totalVolumeMilliM3:30_000,composition:comp})});
 it('keeps owner custody and location independent during transfer and move',()=>{const{e,b}=base();go(e,'CUST','TransferCustody',{objectType:'BATCH',objectId:'BATCH-000001',custodyActorId:'custodian.second'});go(e,'MOVE','MoveBatch',{batchId:'BATCH-000001',toLocationId:b});const x=e.inventory.batch('BATCH-000001')!;expect(x).toMatchObject({ownerCompanyId:'COMPANY-000001',custodyActorId:'custodian.second',locationId:b,currentVolumeMilliM3:100_000})});
 it('requires an open route and never teleports',()=>{const{e,b}=base();go(e,'BLOCK','SetRouteEdgeAccess',{edgeId:'EDGE-000001',accessState:'BLOCKED'});const before=e.auditFingerprint();expect(go(e,'MOVE','MoveBatch',{batchId:'BATCH-000001',toLocationId:b}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.inventory.batch('BATCH-000001')!.locationId).toBe('LOCATION-000001')});
 it('depletes an available quantity exactly once',()=>{const{e}=base();go(e,'DEP','DepleteBatch',{batchId:'BATCH-000001',volumeMilliM3:1_001});expect(inventoryReconciliation(e)).toMatchObject({currentPhysicalVolumeMilliM3:98_999,depletedVolumeMilliM3:1_001,reconciles:true});expect(go(e,'BAD','DepleteBatch',{batchId:'BATCH-000001',volumeMilliM3:99_000}).accepted).toBe(false)});
 it('cost attribution never changes finance cash or transactions',()=>{const{e}=base(),before=e.finance.snapshot();go(e,'COST','AddCostLayer',{attachedToType:'DEAL',attachedToId:'DEAL-000001',sourceObjectId:'x',category:'ACQUISITION',currency:'EUR',totalMinor:25_000,attributableVolumeMilliM3:100_000,provenanceReference:'prov.tunable'});expect(e.finance.snapshot()).toEqual(before);expect(costReconciliation(e).activeAttributedMinor).toBe(25_000)});
 it('save load and replay preserve active reservations, counters and checksum',()=>{const{e,companyId}=base();const snap=createSnapshot(e);go(e,'R','CreateInventoryReservation',{companyId,batchId:'BATCH-000001',purpose:'x',sourceObjectId:'x',volumeMilliM3:123,expectedReleaseTimestamp:5000});const save=createSave(e,snap),loaded=loadSave(save),replayed=replayEventsFromSnapshot(save);expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(replayed.stateChecksum()).toBe(e.stateChecksum());expect(loaded.ids.next('reservation','RESERVATION')).toBe('RESERVATION-000002')});
 it('migrates a version-3 fixture, preserves Step 1–4 state, and replays deterministically',()=>{const legacy=mk();go(legacy,'C','CreateCompany',{displayName:'Legacy',reputationBasisPoints:5000});const save:any=createSave(legacy,createSnapshot(legacy));delete save.snapshot.state.inventory;save.snapshot.snapshotSchemaVersion=3;const{snapshotChecksum:oldSnapshotChecksum,...snapshotBare}=save.snapshot;save.snapshot.snapshotChecksum=snapshotChecksum(snapshotBare);save.saveSchemaVersion=3;save.coreVersion='0.4.0';const{saveChecksum:oldSaveChecksum,...saveBare}=save;save.saveChecksum=calculateSaveChecksum(saveBare);const loaded=loadSave(save);expect(loaded.finance.snapshot()).toEqual(legacy.finance.snapshot());expect(loaded.routing.snapshot()).toEqual(legacy.routing.snapshot());expect(loaded.inventory.snapshot()).toEqual({appliedEventIds:[],deals:[],lots:[],batches:[],loads:[],reservations:[],allocations:[],costLayers:[]});expect(loaded.stateChecksum()).toBe(legacy.stateChecksum())});
 it('read models are defensive and RNG-free',()=>{const{e}=base(),rng=e.rng.snapshot(),grid:any=inventoryGrid(e),tree:any=dealTree(e,'DEAL-000001');grid[0].owner='bad';tree.deal.description='bad';expect(inventoryGrid(e)[0]!.owner).toBe('COMPANY-000001');expect(dealTree(e,'DEAL-000001')!.deal.description).not.toBe('bad');expect(e.rng.snapshot()).toEqual(rng)});
 it('same seed and commands produce identical state and event checksums',()=>{const a=splitFixture(),b=splitFixture();expect(a.e.stateChecksum()).toBe(b.e.stateChecksum());expect(a.e.eventLogChecksum()).toBe(b.e.eventLogChecksum())});
 it('changing or removing a Step 5 event changes replay outcome',()=>{const{e}=base(),snap=createSnapshot(e);go(e,'DEP','DepleteBatch',{batchId:'BATCH-000001',volumeMilliM3:1});const save=createSave(e,snap),removed={...save,eventsAfterSnapshot:[]};expect(replayEventsFromSnapshot(removed as any).stateChecksum()).not.toBe(e.stateChecksum())});
 it('duplicate inventory event application rejects before mutation',()=>{const{e}=base(),event=e.eventLog.all().find(x=>x.eventType==='BatchCreated')!,before=e.stateChecksum();expect(()=>e.inventory.apply(event)).toThrow('Duplicate inventory event');expect(e.stateChecksum()).toBe(before)});
 it.each(Array.from({length:20},(_,i)=>i+1))('generated split partition %i conserves exact volume and awkward cost',i=>{const total=10_000+i,a=i,b=333,c=total-a-b,{e}=base(total);go(e,'COST','AddCostLayer',{attachedToType:'BATCH',attachedToId:'BATCH-000001',sourceObjectId:'x',category:'ACQUISITION',currency:'EUR',totalMinor:997+i,attributableVolumeMilliM3:total,provenanceReference:'prov.tunable'});expect(go(e,'S','SplitBatch',{batchId:'BATCH-000001',childVolumesMilliM3:[a,b,c]}).accepted).toBe(true);expect(inventoryReconciliation(e)).toMatchObject({currentPhysicalVolumeMilliM3:total,reconciles:true});expect(e.inventory.snapshot().costLayers.filter(x=>x.status==='ACTIVE').reduce((n,x)=>n+x.totalMinor,0)).toBe(997+i)});
 it.each(Array.from({length:30},(_,i)=>i))('invalid reservation/depletion case %i is atomic',i=>{const{e,companyId}=base(),before=e.auditFingerprint(),type=i%2?'CreateInventoryReservation':'DepleteBatch',payload=type==='CreateInventoryReservation'?{companyId,batchId:'BATCH-000001',purpose:'x',sourceObjectId:'x',volumeMilliM3:100_001+i}:{batchId:'BATCH-000001',volumeMilliM3:100_001+i};expect(go(e,'BAD',type,payload).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('deterministic repeated split merge allocation stress preserves invariants',()=>{const{e,companyId,a}=base(120_000);go(e,'S','SplitBatch',{batchId:'BATCH-000001',childVolumesMilliM3:Array(12).fill(10_000)});for(let i=0;i<6;i++)go(e,'M'+i,'MergeBatches',{batchIds:[`BATCH-${String(2+i*2).padStart(6,'0')}`,`BATCH-${String(3+i*2).padStart(6,'0')}`]});for(let i=0;i<6;i++){go(e,'L'+i,'CreateLoad',{ownerCompanyId:companyId,custodyActorId:'custodian.demo',originLocationId:a});go(e,'A'+i,'AllocateBatchToLoad',{batchId:`BATCH-${String(14+i).padStart(6,'0')}`,loadId:`LOAD-${String(1+i).padStart(6,'0')}`,volumeMilliM3:10_000})}expect(inventoryReconciliation(e).reconciles).toBe(true);expect(()=>e.inventory.assertInvariants()).not.toThrow()});
 it('integer weighted composition and remainder allocation are stable',()=>{expect(allocateInteger(10,[1,1,1])).toEqual([4,3,3]);const x=weightedComposition([{volume:1,composition:comp},{volume:2,composition:comp}]);expect(x).toEqual(comp)});
});
