import{describe,expect,it}from'vitest';import{command,SimulationEngine}from'../src/core/engine.js';import{calculateSaveChecksum,createSave,loadSave}from'../src/persistence/save.js';import{createSnapshot,snapshotChecksum}from'../src/persistence/snapshot.js';import{intelFeed,offerView,supplierContactView,supplierDirectory}from'../src/supplier/read-models.js';import{financeHeader}from'../src/finance/read-models.js';const comp={species:[{id:'species.birch',basisPoints:10000}],assortment:[{id:'assortment.pulpwood',basisPoints:10000}],quality:[{id:'quality.birch.a',basisPoints:500},{id:'quality.birch.b',basisPoints:5000},{id:'quality.birch.tara_c',basisPoints:4000},{id:'quality.birch.brakis',basisPoints:500}]};const mk=()=>new SimulationEngine({seed:'supplier-step-7',configurationBundleVersion:'1',configurationHash:'h',scenarioId:'s',clock:{paused:false}}),go=(e:SimulationEngine,n:string,t:string,p:any={})=>e.execute(command(n,t,e,p));
function base(reliability=6500,paymentExpectation=100){const e=mk();go(e,'C','CreateCompany',{displayName:'Mežtirgus SIA',reputationBasisPoints:5000});go(e,'CASH','CreateOpeningBalance',{companyId:'COMPANY-000001',amountMinor:1_000_000});go(e,'LOC','CreateLocation',{displayName:'Cēsis roadside',countryCode:'LV',regionCode:'VIDZEME',roles:['ROADSIDE']});go(e,'SUP','CreateSupplier',{configId:'supplier.liepa_owner',displayName:'Liepa Private Forest Owner',fictional:true,archetype:'PRIVATE_FOREST_OWNER',companyId:'COMPANY-000001',locationId:'LOCATION-000001',channels:['PRIVATE_ROADSIDE_OFFER'],suppliedSpeciesIds:['species.birch'],suppliedAssortmentIds:['assortment.pulpwood'],paymentExpectationSeconds:paymentExpectation,documentReliabilityBasisPoints:6500,freshnessAnswerReliabilityBasisPoints:reliability,initialRelationshipBasisPoints:2500});go(e,'CONTACT','CreateSupplierContact',{supplierId:'SUPPLIER-000001',displayName:'Jānis Liepa',role:'OWNER'});return e}
function offer(e:SimulationEngine,id='O',expiry=100,basis='AGREED_VOLUME'){return go(e,id,'CreateOffer',{supplierId:'SUPPLIER-000001',contactId:'CONTACT-000001',companyId:'COMPANY-000001',locationId:'LOCATION-000001',expiryTimestamp:expiry,volumeBasis:basis,offeredVolumeMilliM3:30_000,baseRateMinorPerM3:5_000,requiredDocumentTypes:['OWNERSHIP_PROOF','FELLING_PERMISSION'],beliefVolumeMinMilliM3:25_000,beliefVolumeMaxMilliM3:35_000,initialBeliefConfidenceBasisPoints:1500,actualVolumeMilliM3:31_234,actualFreshness:'FRESH',truthComposition:comp})}
function documents(e:SimulationEngine,offerNo=1){const set=`DOCSET-${String(offerNo).padStart(6,'0')}`;for(const [i,type]of['OWNERSHIP_PROOF','FELLING_PERMISSION'].entries())go(e,`DOC${offerNo}.${i}`,'AddDocument',{documentSetId:set,documentType:type,issuer:'Fictional authority',reference:`REF-${offerNo}-${i}`,validFromTimestamp:0,validUntilTimestamp:1000});return go(e,`VAL${offerNo}`,'ValidateDocumentSet',{documentSetId:set})}
describe('Step 7 suppliers, offers, documents, relationships, and intel',()=>{
 it('creates valid fictional supplier, relationship and contact with deterministic IDs',()=>{const e=base();expect(e.suppliers.supplier('SUPPLIER-000001')).toMatchObject({fictional:true,displayName:'Liepa Private Forest Owner'});expect(e.suppliers.contact('CONTACT-000001')!.displayName).toBe('Jānis Liepa');expect(e.suppliers.relationship('RELATIONSHIP-000001')!.warmthBasisPoints).toBe(2500)});
 it('invalid supplier and contact creation reject atomically',()=>{const e=mk();for(const[t,p]of[['CreateSupplier',{}],['CreateSupplierContact',{supplierId:'NO'}]]as Array<[string,any]>){const before=e.auditFingerprint();expect(go(e,'BAD',t,p).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)}});
 it('creates an open offer and exact scheduled expiry',()=>{const e=base();offer(e);expect(e.suppliers.offer('OFFER-000001')).toMatchObject({status:'OPEN',expiryTimestamp:100});expect(e.queue.snapshot().find(x=>x.eventType==='OfferExpired')!.scheduledGameTime).toBe(100)});
 it('expires exactly and stale expiry after rejection is safe',()=>{const e=base();offer(e);e.advanceUntil(99);expect(e.suppliers.offer('OFFER-000001')!.status).toBe('OPEN');e.advanceUntil(100);expect(e.suppliers.offer('OFFER-000001')!.status).toBe('EXPIRED');offer(e,'O2',200);go(e,'R','RejectOffer',{offerId:'OFFER-000002'});e.advanceUntil(200);expect(e.suppliers.offer('OFFER-000002')!.status).toBe('REJECTED')});
 it('rejects acceptance at or after expiry atomically',()=>{const e=base();offer(e);documents(e);e.advanceUntil(100);const before=e.auditFingerprint();expect(go(e,'A','AcceptOffer',{offerId:'OFFER-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
 it('ordinary offer view separates belief and never exposes hidden truth',()=>{const e=base();offer(e);const view:any=offerView(e,'OFFER-000001');expect(view.truth).toBeUndefined();expect(view.belief).toMatchObject({estimatedVolumeMinMilliM3:25_000,estimatedVolumeMaxMilliM3:35_000,freshnessBelief:'UNKNOWN'})});
 it('inspection narrows belief without revealing exact volume truth',()=>{const e=base();offer(e);const before=offerView(e,'OFFER-000001')!.belief;go(e,'I','InspectOffer',{offerId:'OFFER-000001'});const after=offerView(e,'OFFER-000001')!.belief;expect(after.estimatedVolumeMaxMilliM3-after.estimatedVolumeMinMilliM3).toBeLessThan(before.estimatedVolumeMaxMilliM3-before.estimatedVolumeMinMilliM3);expect(after.estimatedVolumeMinMilliM3).not.toBe(after.estimatedVolumeMaxMilliM3);expect(after.confidenceBasisPoints).toBeGreaterThan(before.confidenceBasisPoints)});
 it('freshness answers use configured fictional reliability and stored RNG outcome',()=>{const a=base(10_000),b=base(10_000);offer(a);offer(b);go(a,'Q','AskFreshnessQuestion',{offerId:'OFFER-000001'});go(b,'Q','AskFreshnessQuestion',{offerId:'OFFER-000001'});expect(a.suppliers.offer('OFFER-000001')!.belief).toEqual(b.suppliers.offer('OFFER-000001')!.belief);expect(a.suppliers.offer('OFFER-000001')!.belief.freshnessBelief).toBe('FRESH')});
 it('missing documents produce an explicit terminal failure and no chain',()=>{const e=base();offer(e);go(e,'VAL','ValidateDocumentSet',{documentSetId:'DOCSET-000001'});expect(go(e,'A','AcceptOffer',{offerId:'OFFER-000001'}).accepted).toBe(true);expect(e.suppliers.offer('OFFER-000001')!.status).toBe('FAILED_DOCUMENTS');expect(e.inventory.snapshot().deals).toHaveLength(0);expect(e.finance.snapshot().payables).toHaveLength(0)});
 it('valid documents permit acceptance before expiry',()=>{const e=base();offer(e);documents(e);expect(e.suppliers.documentSet('DOCSET-000001')).toMatchObject({status:'VALID',missingTypes:[]});expect(go(e,'A','AcceptOffer',{offerId:'OFFER-000001'}).accepted).toBe(true)});
 it('acceptance creates Offer → Deal → Lot → Batch → commitment/payable exactly once',()=>{const e=base();offer(e);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});expect(e.suppliers.offer('OFFER-000001')).toMatchObject({status:'ACCEPTED',dealId:'DEAL-000001',lotId:'LOT-000001',batchId:'BATCH-000001',commitmentId:'COMMITMENT-000001',payableId:'PAYABLE-000001'});expect(e.inventory.snapshot()).toMatchObject({deals:[{id:'DEAL-000001'}],lots:[{id:'LOT-000001'}],batches:[{id:'BATCH-000001'}]});expect(e.finance.snapshot()).toMatchObject({commitments:[{id:'COMMITMENT-000001'}],payables:[{id:'PAYABLE-000001'}]});const before=e.auditFingerprint();expect(go(e,'A2','AcceptOffer',{offerId:'OFFER-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.finance.snapshot().payables).toHaveLength(1)});
 it('agreed-volume basis controls physical and payable quantities',()=>{const e=base();offer(e);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});expect(e.inventory.batch('BATCH-000001')!.currentVolumeMilliM3).toBe(30_000);expect(e.finance.payable('PAYABLE-000001')!.principalMinor).toBe(149_940)});
 it('mill-measured basis retains explicit placeholder linkage',()=>{const e=base();offer(e,'O',100,'MILL_MEASURED_VOLUME_PLACEHOLDER');documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});expect(e.suppliers.offer('OFFER-000001')!.volumeBasis).toBe('MILL_MEASURED_VOLUME_PLACEHOLDER');expect(e.inventory.batch('BATCH-000001')!.certainty).toBe('ESTIMATED')});
 it('offer acceptance recognizes payable without mutating cash',()=>{const e=base(),cash=financeHeader(e,'COMPANY-000001').cashBalanceMinor;offer(e);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(cash);expect(financeHeader(e,'COMPANY-000001').freeCashMinor).toBeLessThan(cash)});
 it('fast settlement improves relationship through explicit events',()=>{const e=base();offer(e);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});go(e,'PAY','RecordPayablePayment',{payableId:'PAYABLE-000001',amountMinor:e.finance.payable('PAYABLE-000001')!.principalMinor});go(e,'OUT','RecordSupplierSettlementOutcome',{offerId:'OFFER-000001'});expect(e.suppliers.relationship('RELATIONSHIP-000001')).toMatchObject({warmthBasisPoints:3000,trustBasisPoints:2800});expect(e.finance.commitment('COMMITMENT-000001')!.status).toBe('SETTLED')});
 it('late settlement damages relationship',()=>{const e=base(6500,10);offer(e, 'O',100);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});e.advanceUntil(11);go(e,'PAY','RecordPayablePayment',{payableId:'PAYABLE-000001',amountMinor:e.finance.payable('PAYABLE-000001')!.principalMinor});go(e,'OUT','RecordSupplierSettlementOutcome',{offerId:'OFFER-000001'});expect(e.suppliers.relationship('RELATIONSHIP-000001')).toMatchObject({warmthBasisPoints:1500,trustBasisPoints:1000})});
 it('fast payment improves the relationship adjustment on a future offer',()=>{const e=base();offer(e);documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});go(e,'PAY','RecordPayablePayment',{payableId:'PAYABLE-000001',amountMinor:e.finance.payable('PAYABLE-000001')!.principalMinor});go(e,'OUT','RecordSupplierSettlementOutcome',{offerId:'OFFER-000001'});offer(e,'O2',200);expect(e.suppliers.offer('OFFER-000002')!.effectiveRateMinorPerM3).toBeLessThan(e.suppliers.offer('OFFER-000001')!.effectiveRateMinorPerM3)});
 it('favor can be gained and consumed by gossip exactly once',()=>{const e=base();go(e,'F','AddRelationshipEvent',{relationshipId:'RELATIONSHIP-000001',warmthDeltaBasisPoints:0,trustDeltaBasisPoints:0,favorDeltaBasisPoints:1000,reason:'HELPED_CONTACT'});go(e,'G','ShareGossip',{contactId:'CONTACT-000001',relationshipId:'RELATIONSHIP-000001',subjectId:'market.pulp',summary:'Cēsis roadside supply is tightening.',confidenceBasisPoints:6000,favorCostBasisPoints:400});expect(e.suppliers.relationship('RELATIONSHIP-000001')!.favorBalanceBasisPoints).toBe(600);expect(intelFeed(e)[0]).toMatchObject({sourceId:'CONTACT-000001',confidenceBasisPoints:6000,kind:'GOSSIP'})});
 it('intel tracks source, confidence, visibility, time, and causes',()=>{const e=base();go(e,'I1','CreateIntelItem',{subjectId:'market.pulp',sourceId:'CONTACT-000001',summary:'Visible report',confidenceBasisPoints:7000,visibility:'PLAYER_VISIBLE',causalEventIds:['EVENT-000003']});go(e,'I2','CreateIntelItem',{subjectId:'supplier.hidden',sourceId:'private.source',summary:'Private source truth',confidenceBasisPoints:9000,visibility:'PRIVATE_SOURCE',causalEventIds:[]});expect(intelFeed(e)).toHaveLength(1);expect(intelFeed(e)[0]).toMatchObject({sourceId:'CONTACT-000001',createdTimestamp:0,causalEventIds:['EVENT-000003']})});
 it('read models are defensive, RNG-free, and truth-safe',()=>{const e=base();offer(e);const rng=e.rng.snapshot(),directory:any=supplierDirectory(e),view:any=supplierContactView(e,'SUPPLIER-000001');directory[0].displayName='bad';view.contacts[0].displayName='bad';expect(supplierDirectory(e)[0]!.displayName).not.toBe('bad');expect((offerView(e,'OFFER-000001')as any).truth).toBeUndefined();expect(view.supplier.freshnessAnswerReliabilityBasisPoints).toBeUndefined();expect(e.rng.snapshot()).toEqual(rng)});
 it('save/load/replay preserves active expiry, belief RNG, commercial links and checksums',()=>{const e=base();offer(e);const snap=createSnapshot(e);go(e,'Q','AskFreshnessQuestion',{offerId:'OFFER-000001'});documents(e);go(e,'A','AcceptOffer',{offerId:'OFFER-000001'});const loaded=loadSave(createSave(e,snap));expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(loaded.suppliers.snapshot()).toEqual(e.suppliers.snapshot());expect(loaded.ids.next('offer','OFFER')).toBe('OFFER-000002')});
 it('migrates version 5 while preserving Steps 1–6',()=>{const legacy=base(),save:any=createSave(legacy,createSnapshot(legacy));delete save.snapshot.state.suppliers;save.snapshot.snapshotSchemaVersion=5;const{snapshotChecksum:oldSnapshotChecksum,...snapshotBare}=save.snapshot;save.snapshot.snapshotChecksum=snapshotChecksum(snapshotBare);save.saveSchemaVersion=5;save.coreVersion='0.6.0';const{saveChecksum:oldSaveChecksum,...saveBare}=save;save.saveChecksum=calculateSaveChecksum(saveBare);const loaded=loadSave(save);expect(loaded.finance.snapshot()).toEqual(legacy.finance.snapshot());expect(loaded.buyers.snapshot()).toEqual(legacy.buyers.snapshot());expect(loaded.suppliers.snapshot()).toEqual({appliedEventIds:[],suppliers:[],contacts:[],relationships:[],offers:[],documentSets:[],documents:[],intelItems:[]})});
 it('same seed and commands yield identical checksums',()=>{const a=base(),b=base();offer(a);offer(b);go(a,'Q','AskFreshnessQuestion',{offerId:'OFFER-000001'});go(b,'Q','AskFreshnessQuestion',{offerId:'OFFER-000001'});expect(a.stateChecksum()).toBe(b.stateChecksum());expect(a.eventLogChecksum()).toBe(b.eventLogChecksum())});
 it.each(Array.from({length:15},(_,i)=>i))('invalid offer scalar case %i is atomic and RNG-neutral',i=>{const e=base(),before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'BAD','CreateOffer',{supplierId:'SUPPLIER-000001',contactId:'CONTACT-000001',companyId:'COMPANY-000001',locationId:'LOCATION-000001',expiryTimestamp:i%2?0:1.5,volumeBasis:'AGREED_VOLUME',offeredVolumeMilliM3:30_000,baseRateMinorPerM3:5_000,requiredDocumentTypes:['X'],beliefVolumeMinMilliM3:1,beliefVolumeMaxMilliM3:2,actualVolumeMilliM3:1,actualFreshness:'FRESH',truthComposition:comp}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
 it('contains no Step 14 market state',()=>{const s:any=base().authoritativeState();expect(s.markets).toBeUndefined()});
});
