import{describe,expect,it}from'vitest';import{command,SimulationEngine}from'../src/core/engine.js';import{createSave,loadSave,calculateSaveChecksum}from'../src/persistence/save.js';import{createSnapshot,snapshotChecksum}from'../src/persistence/snapshot.js';import{carrierDirectory,carrierQuoteView,transportBoard,transportJobView}from'../src/transport/read-models.js';import{financeHeader}from'../src/finance/read-models.js';
const composition={species:[{id:'species.birch',basisPoints:10000}],assortment:[{id:'assortment.pulpwood',basisPoints:10000}],quality:[{id:'quality.birch.b',basisPoints:10000}]},mk=()=>new SimulationEngine({seed:'transport-step-8',configurationBundleVersion:'1',configurationHash:'h',scenarioId:'s',clock:{paused:false}}),go=(e:SimulationEngine,id:string,type:string,p:any={})=>e.execute(command(id,type,e,p));
function world(capacity=35_000,chance=10_000,directed=true){const e=mk();go(e,'C','CreateCompany',{displayName:'Mežtirgus SIA',reputationBasisPoints:5000});go(e,'CASH','CreateOpeningBalance',{companyId:'COMPANY-000001',amountMinor:1_000_000});go(e,'A','CreateLocation',{displayName:'Cēsis roadside',countryCode:'LV',regionCode:'VIDZEME',roles:['ROADSIDE']});go(e,'B','CreateLocation',{displayName:'Rīga buyer',countryCode:'LV',regionCode:'RIGA',roles:['BUYER']});go(e,'R','CreateRouteEdge',{fromLocationId:'LOCATION-000001',toLocationId:'LOCATION-000002',accessClass:'PAVED',distanceMetres:100_000,travelSeconds:7200,directed});go(e,'D','CreateDeal',{companyId:'COMPANY-000001',counterpartyId:'supplier.demo',currency:'EUR',expectedVolumeMilliM3:30_000,description:'transport test',financeSourceIds:[]});go(e,'DA','ActivateDeal',{dealId:'DEAL-000001'});go(e,'L','CreateLot',{dealId:'DEAL-000001',ownerCompanyId:'COMPANY-000001',custodyActorId:'supplier.demo',locationId:'LOCATION-000001',originalVolumeMilliM3:30_000,composition,freshness:'FRESH',certainty:'ESTIMATED'});go(e,'BATCH','CreateInitialBatch',{lotId:'LOT-000001',volumeMilliM3:30_000,composition});go(e,'LOAD','CreateLoad',{ownerCompanyId:'COMPANY-000001',custodyActorId:'supplier.demo',originLocationId:'LOCATION-000001',destinationLocationId:'LOCATION-000002'});go(e,'ALLOC','AllocateBatchToLoad',{batchId:'BATCH-000001',loadId:'LOAD-000001',volumeMilliM3:30_000});go(e,'CAR','CreateCarrier',{configId:'transport.small_trader_spot',displayName:'Vidzemes Kravas',fictional:true,capacityMilliM3:capacity,baseCalloutMinor:10_000,distanceRateMinorPerKm:100,volumeRateMinorPerM3:400,pickupDelaySeconds:600,paymentTermsSeconds:3600,disruptionChanceBasisPoints:chance,disruptionDelaySeconds:900,disruptionSurchargeMinor:2_000});return e}
function quote(e:SimulationEngine,id='Q',expiry=1000,dest='LOCATION-000002'){return go(e,id,'RequestCarrierQuote',{carrierId:'CARRIER-000001',loadId:'LOAD-000001',destinationLocationId:dest,expiryTimestamp:expiry,urgencyBasisPoints:1000})}function job(e:SimulationEngine){quote(e);go(e,'QA','AcceptCarrierQuote',{quoteId:'QUOTE-000001'});go(e,'J','CreateTransportJob',{quoteId:'QUOTE-000001'});return go(e,'JA','AllocateLoadToTransportJob',{jobId:'JOB-000001'})}function dispatch(e:SimulationEngine){job(e);return go(e,'GO','ConfirmDispatch',{jobId:'JOB-000001'})}
describe('Step 8 hired logistics and paused manual dispatch',()=>{
it('creates valid fictional carriers with deterministic IDs',()=>{const e=world();expect(e.transport.carrier('CARRIER-000001')).toMatchObject({displayName:'Vidzemes Kravas',fictional:true,capacityMilliM3:35_000})});
it('rejects invalid carrier creation atomically',()=>{const e=mk(),before=e.auditFingerprint();expect(go(e,'BAD','CreateCarrier',{}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('creates deterministic quote IDs and inspectable integer pricing',()=>{const e=world();quote(e);expect(carrierQuoteView(e,'QUOTE-000001')).toMatchObject({distanceMetres:100_000,travelSeconds:7200,breakdown:{baseCalloutMinor:10_000,distanceCostMinor:10_000,volumeCostMinor:12_000,urgencyAdjustmentMinor:3_200,finalTotalMinor:35_200}})});
it('quote expires exactly and expiry is stale after acceptance',()=>{const e=world();quote(e,'Q',100);e.advanceUntil(99);expect(e.transport.quote('QUOTE-000001')!.status).toBe('OPEN');e.advanceUntil(100);expect(e.transport.quote('QUOTE-000001')!.status).toBe('EXPIRED');quote(e,'Q2',200);go(e,'A','AcceptCarrierQuote',{quoteId:'QUOTE-000002'});e.advanceUntil(200);expect(e.transport.quote('QUOTE-000002')!.status).toBe('ACCEPTED')});
it('uses directed and asymmetric route behavior',()=>{const e=world();expect(quote(e,'Q',1000,'LOCATION-000002').accepted).toBe(true);expect(()=>e.routing.route('LOCATION-000002','LOCATION-000001')).toThrow('NO_ROUTE')});
it('blocked route rejects without mutation',()=>{const e=world();go(e,'BLOCK','SetRouteEdgeAccess',{edgeId:'EDGE-000001',accessState:'BLOCKED'});const before=e.auditFingerprint();expect(quote(e).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('enforces capacity and permits exact capacity',()=>{expect(quote(world(29_999)).accepted).toBe(false);expect(quote(world(30_000)).accepted).toBe(true)});
it('acceptance and job creation do not move cargo',()=>{const e=world();job(e);expect(e.transport.job('JOB-000001')!.status).toBe('WAITING_CONFIRMATION');expect(e.inventory.load('LOAD-000001')).toMatchObject({currentLocationId:'LOCATION-000001',custodyActorId:'supplier.demo'});expect(e.queue.snapshot().some(x=>x.eventType==='TransportJobArrived')).toBe(false);expect(e.finance.snapshot().payables).toHaveLength(0)});
it('prevents one load entering multiple active jobs',()=>{const e=world();job(e);quote(e,'Q2');go(e,'A2','AcceptCarrierQuote',{quoteId:'QUOTE-000002'});go(e,'J2','CreateTransportJob',{quoteId:'QUOTE-000002'});const before=e.auditFingerprint();expect(go(e,'JA2','AllocateLoadToTransportJob',{jobId:'JOB-000002'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('dispatch requires explicit confirmation and cannot duplicate',()=>{const e=world();dispatch(e);expect(e.transport.job('JOB-000001')!.status).toBe('DISPATCHED');const before=e.auditFingerprint();expect(go(e,'GO2','ConfirmDispatch',{jobId:'JOB-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('confirmation atomically revalidates a still-open quoted route',()=>{const e=world();job(e);go(e,'BLOCK','SetRouteEdgeAccess',{edgeId:'EDGE-000001',accessState:'BLOCKED'});const before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'GO','ConfirmDispatch',{jobId:'JOB-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
it('schedules exact pickup, disruption, and delayed arrival',()=>{const e=world();dispatch(e);const j=e.transport.job('JOB-000001')!;expect(j.pickupTimestamp).toBe(600);expect(j.plannedArrivalTimestamp).toBe(8700);expect(e.queue.snapshot().map(x=>[x.eventType,x.scheduledGameTime])).toEqual(expect.arrayContaining([['TransportPickupRecorded',600],['TransportDisruptionRecorded',4200],['TransportJobArrived',8700]]))});
it('pickup changes custody but never ownership or location',()=>{const e=world();dispatch(e);e.advanceUntil(600);expect(e.inventory.load('LOAD-000001')).toMatchObject({ownerCompanyId:'COMPANY-000001',custodyActorId:'CARRIER-000001',currentLocationId:'LOCATION-000001'});expect(e.transport.job('JOB-000001')!.status).toBe('IN_TRANSIT')});
it('arrival occurs at the calculated timestamp without teleporting early',()=>{const e=world();dispatch(e);e.advanceUntil(8699);expect(e.inventory.load('LOAD-000001')!.currentLocationId).toBe('LOCATION-000001');e.advanceUntil(8700);expect(e.inventory.load('LOAD-000001')).toMatchObject({currentLocationId:'LOCATION-000002',ownerCompanyId:'COMPANY-000001',custodyActorId:'CARRIER-000001'});expect(e.transport.job('JOB-000001')!.status).toBe('ARRIVED')});
it('deterministic disruption material is stored in the confirmation event',()=>{const a=world(),b=world();dispatch(a);dispatch(b);const x=a.eventLog.all().find(e=>e.eventType==='TransportDispatchConfirmed')!,y=b.eventLog.all().find(e=>e.eventType==='TransportDispatchConfirmed')!;expect(x.payload).toEqual(y.payload);expect(x.payload.useTransportRng).toBe(true)});
it('unload restores owner custody and completion creates one payable and cost layer',()=>{const e=world();dispatch(e);e.advanceUntil(8700);go(e,'U','UnloadTransportJob',{jobId:'JOB-000001'});expect(e.inventory.load('LOAD-000001')).toMatchObject({status:'UNLOADED',ownerCompanyId:'COMPANY-000001',custodyActorId:'COMPANY-000001'});const cash=financeHeader(e,'COMPANY-000001').cashBalanceMinor;go(e,'DONE','CompleteTransportJob',{jobId:'JOB-000001'});expect(e.transport.job('JOB-000001')).toMatchObject({status:'COMPLETED',payableId:'PAYABLE-000001',finalCostMinor:37_200});expect(e.finance.payable('PAYABLE-000001')!.principalMinor).toBe(37_200);expect(e.inventory.load('LOAD-000001')!.costLayerIds).toEqual(['COST-000001']);expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(cash);const before=e.auditFingerprint();expect(go(e,'DONE2','CompleteTransportJob',{jobId:'JOB-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('carrier payable settles only through existing finance commands',()=>{const e=world();dispatch(e);e.advanceUntil(8700);go(e,'U','UnloadTransportJob',{jobId:'JOB-000001'});go(e,'DONE','CompleteTransportJob',{jobId:'JOB-000001'});const before=financeHeader(e,'COMPANY-000001').cashBalanceMinor;go(e,'PAY','RecordPayablePayment',{payableId:'PAYABLE-000001',amountMinor:37_200});expect(e.finance.payable('PAYABLE-000001')!.status).toBe('PAID');expect(financeHeader(e,'COMPANY-000001').cashBalanceMinor).toBe(before-37_200)});
it('cancels before dispatch without movement or cost',()=>{const e=world();job(e);go(e,'X','CancelTransportJob',{jobId:'JOB-000001'});expect(e.transport.job('JOB-000001')!.status).toBe('CANCELLED');expect(e.inventory.load('LOAD-000001')!.currentLocationId).toBe('LOCATION-000001');expect(e.finance.snapshot().payables).toHaveLength(0)});
it('cancellation after dispatch makes pickup, disruption, and arrival stale',()=>{const e=world();dispatch(e);go(e,'X','CancelTransportJob',{jobId:'JOB-000001'});e.advanceUntil(9000);expect(e.transport.job('JOB-000001')!.status).toBe('CANCELLED');expect(e.inventory.load('LOAD-000001')).toMatchObject({currentLocationId:'LOCATION-000001',custodyActorId:'supplier.demo'});expect(e.finance.snapshot().payables).toHaveLength(0)});
it('cancellation after pickup is explicitly rejected',()=>{const e=world();dispatch(e);e.advanceUntil(600);const before=e.auditFingerprint();expect(go(e,'X','CancelTransportJob',{jobId:'JOB-000001'}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before)});
it('zero disruption branch preserves base quote total and omits disruption event',()=>{const e=world(35_000,0);dispatch(e);const j=e.transport.job('JOB-000001')!;expect(j.disruptionDelaySeconds).toBe(0);expect(j.finalCostMinor).toBe(35_200);expect(e.queue.snapshot().some(x=>x.eventType==='TransportDisruptionRecorded')).toBe(false)});
it('save/load/replay preserves scheduled movement, RNG, and checksums',()=>{const e=world(),snap=createSnapshot(e);dispatch(e);e.advanceUntil(600);const loaded=loadSave(createSave(e,snap));expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(loaded.transport.snapshot()).toEqual(e.transport.snapshot());loaded.advanceUntil(8700);e.advanceUntil(8700);expect(loaded.stateChecksum()).toBe(e.stateChecksum());expect(loaded.ids.next('transport_job','JOB')).toBe('JOB-000002')});
it('migrates version 6 while preserving Steps 1–7',()=>{const legacy=world(),save:any=createSave(legacy,createSnapshot(legacy));delete save.snapshot.state.transport;save.snapshot.snapshotSchemaVersion=6;const{snapshotChecksum:_,...bare}=save.snapshot;save.snapshot.snapshotChecksum=snapshotChecksum(bare);save.saveSchemaVersion=6;save.coreVersion='0.7.0';const{saveChecksum:__,...saveBare}=save;save.saveChecksum=calculateSaveChecksum(saveBare);const loaded=loadSave(save);expect(loaded.inventory.snapshot()).toEqual(legacy.inventory.snapshot());expect(loaded.suppliers.snapshot()).toEqual(legacy.suppliers.snapshot());expect(loaded.transport.snapshot()).toEqual({appliedEventIds:[],carriers:[],quotes:[],jobs:[]})});
it('read models are defensive and RNG-free',()=>{const e=world();dispatch(e);const rng=e.rng.snapshot(),directory:any=carrierDirectory(e),board:any=transportBoard(e);directory[0].displayName='bad';board[0].status='FAILED';expect(carrierDirectory(e)[0]!.displayName).toBe('Vidzemes Kravas');expect(transportJobView(e,'JOB-000001')!.status).toBe('DISPATCHED');expect(e.rng.snapshot()).toEqual(rng)});
it('UTF-8 Latvian carrier and locations round-trip',()=>{const e=world();expect(carrierDirectory(e)[0]!.displayName).toBe('Vidzemes Kravas');expect(e.routing.location('LOCATION-000001')!.displayName).toBe('Cēsis roadside');const loaded=loadSave(createSave(e,createSnapshot(e)));expect(loaded.routing.location('LOCATION-000001')!.displayName).toBe('Cēsis roadside')});
it('same seed and commands produce identical checksums',()=>{const a=world(),b=world();dispatch(a);dispatch(b);expect(a.stateChecksum()).toBe(b.stateChecksum());expect(a.eventLogChecksum()).toBe(b.eventLogChecksum())});
it.each(Array.from({length:12},(_,i)=>i))('rejection path %i is atomic and RNG-neutral',i=>{const e=world(),before=e.auditFingerprint(),rng=e.rng.snapshot();expect(go(e,'BAD','RequestCarrierQuote',{carrierId:'CARRIER-000001',loadId:'LOAD-000001',destinationLocationId:'LOCATION-000002',expiryTimestamp:i%2?0:1.5,urgencyBasisPoints:0}).accepted).toBe(false);expect(e.auditFingerprint()).toBe(before);expect(e.rng.snapshot()).toEqual(rng)});
it('contains no Step 13 export or market state',()=>{const s:any=world().authoritativeState();expect(s.exports).toBeUndefined();expect(s.markets).toBeUndefined()});
});
