import {command,SimulationEngine} from "../core/engine.js";
import {createSnapshot} from "../persistence/snapshot.js";
import {createSave,loadSave} from "../persistence/save.js";
import {financeHeader,ledgerList,loanSummary,payableAging,receivableAging} from "../finance/read-models.js";
const e=new SimulationEngine({seed:"finance-demo",configurationBundleVersion:"1.0.0",configurationHash:"demo",scenarioId:"scenario.first_full",clock:{paused:false}});
const run=(id:string,type:string,payload:Record<string,unknown>)=>{const result=e.execute(command(id,type,e,payload));if(!result.accepted)throw new Error(`${result.code}: ${result.message}`);};
const show=(label:string,value:unknown)=>console.log(`${label}: ${JSON.stringify(value)}`);
run("COMPANY","CreateCompany",{displayName:"Mežtirgus SIA",reputationBasisPoints:5000});
const companyId=e.finance.snapshot().companies[0]!.id;
run("OPENING","CreateOpeningBalance",{companyId,amountMinor:3_000_000,difficulty:"NORMAL"});
const replayBase=createSnapshot(e);
show("opening",financeHeader(e,companyId));
run("COMMIT","CreateCommitment",{companyId,amountMinor:500_000,purpose:"Yard operating deposit",counterpartyId:"COUNTERPARTY-DEMO"});
const commitmentId=e.finance.snapshot().commitments[0]!.id;
show("commitment_reserved_cash_unchanged_free_cash_lower",financeHeader(e,companyId));
run("RELEASE","ReleaseCommitment",{commitmentId});
show("commitment_released",financeHeader(e,companyId));
run("RECEIVABLE","CreateReceivable",{companyId,counterpartyId:"BUYER-DEMO",principalMinor:750_000,dueTimestamp:3600});
show("receivable_recognized_cash_unchanged",financeHeader(e,companyId));
run("PAYABLE","CreatePayable",{companyId,counterpartyId:"SUPPLIER-DEMO",principalMinor:200_000,dueTimestamp:3600});
run("LOAN","OfferLoan",{companyId,lenderId:"BANK-DEMO",offerPrincipalMinor:5_000_000,annualRateBasisPoints:800,maturityTimestamp:730*86400});
const loanId=e.finance.snapshot().loans[0]!.id;
run("ACCEPT","AcceptLoan",{loanId});run("DRAW","DrawLoan",{loanId,amountMinor:2_000_000});
run("CREDIT","CreateCreditFacility",{companyId,lenderId:"BANK-DEMO",limitMinor:2_500_000,annualRateBasisPoints:1000,reviewTimestamp:30*86400});
e.advanceUntil(86400);
show("claims_after_due_boundary",{receivables:receivableAging(e,companyId),payables:payableAging(e,companyId)});
run("COLLECT","RecordReceivablePayment",{receivableId:e.finance.snapshot().receivables[0]!.id,amountMinor:750_000});
run("PAY","RecordPayablePayment",{payableId:e.finance.snapshot().payables[0]!.id,amountMinor:200_000});
run("INTEREST","AccrueLoanInterest",{loanId,throughTimestamp:86400});
const interest=e.finance.loan(loanId)!.accruedInterestMinor;
run("REPAY","RepayLoan",{loanId,amountMinor:interest+100_000});
show("final_finance_header",financeHeader(e,companyId));
show("loan_summary",loanSummary(e,companyId));
show("ledger",ledgerList(e,companyId));
const save=createSave(e,replayBase),loaded=loadSave(save);
show("save_load_replay",{originalStateChecksum:e.stateChecksum(),loadedStateChecksum:loaded.stateChecksum(),stateChecksumsMatch:e.stateChecksum()===loaded.stateChecksum(),originalEventChecksum:e.eventLogChecksum(),loadedPostSnapshotEventChecksum:loaded.eventLogChecksum(),financeStateMatches:JSON.stringify(e.finance.snapshot())===JSON.stringify(loaded.finance.snapshot())});
