import type { SimulationEngine } from "../core/engine.js";import { accountId } from "./domain.js";
export interface FinanceHeader{cashBalanceMinor:number;restrictedCashMinor:number;activeCommitmentsMinor:number;freeCashMinor:number;availableCreditMinor:number;totalLiquidityMinor:number;receivablesMinor:number;}
export function financeHeader(e:SimulationEngine,companyId:string):FinanceHeader{const s=e.finance.snapshot(),cash=e.finance.balance(accountId(companyId,"OPERATING_CASH")),restricted=e.finance.balance(accountId(companyId,"RESTRICTED_CASH")),committed=s.commitments.filter((x)=>x.companyId===companyId&&x.status==="ACTIVE").reduce((n,x)=>n+x.amountMinor,0),receivables=s.receivables.filter((x)=>x.companyId===companyId&&x.status!=="PAID").reduce((n,x)=>n+x.principalMinor-x.amountPaidMinor,0);const freeCash=cash-committed,availableCredit=s.creditFacilities.filter((x)=>x.companyId===companyId&&x.eligible&&(x.status==="AVAILABLE"||x.status==="ACTIVE")).reduce((n,x)=>n+x.limitMinor-x.drawnMinor,0);return{cashBalanceMinor:cash,restrictedCashMinor:restricted,activeCommitmentsMinor:committed,freeCashMinor:freeCash,availableCreditMinor:availableCredit,totalLiquidityMinor:freeCash+availableCredit,receivablesMinor:receivables};}
export function ledgerList(e:SimulationEngine,companyId:string){return e.finance.transactions().filter((x)=>x.companyId===companyId);}
export function cashLedgerEntries(e:SimulationEngine,companyId:string){const cashAccount=accountId(companyId,"OPERATING_CASH");return ledgerList(e,companyId).flatMap((transaction)=>transaction.lines.filter((line)=>line.accountId===cashAccount).map((line,index)=>({id:`${transaction.id}.cash.${index+1}`,transactionId:transaction.id,timestamp:transaction.timestamp,companyId,accountId:cashAccount,amountMinor:line.debitMinor||line.creditMinor,direction:line.debitMinor>0?"INFLOW" as const:"OUTFLOW" as const,currency:line.currency,category:line.category,...(line.counterpartyId?{counterpartyId:line.counterpartyId}:{}),memo:line.memo,ruleReference:line.ruleReference})));}
export function receivableAging(e:SimulationEngine,companyId:string){return e.finance.snapshot().receivables.filter((x)=>x.companyId===companyId).map((x)=>({...x,outstandingMinor:x.principalMinor-x.amountPaidMinor,ageSeconds:Math.max(0,e.clock.currentGameTime-x.invoiceTimestamp)}));}
export function payableAging(e:SimulationEngine,companyId:string){return e.finance.snapshot().payables.filter((x)=>x.companyId===companyId).map((x)=>({...x,outstandingMinor:x.principalMinor-x.amountPaidMinor,ageSeconds:Math.max(0,e.clock.currentGameTime-x.createdTimestamp)}));}
export function loanSummary(e:SimulationEngine,companyId:string){return e.finance.snapshot().loans.filter((x)=>x.companyId===companyId).map((x)=>({id:x.id,status:x.status,principalMinor:x.principalMinor,accruedInterestMinor:x.accruedInterestMinor,rateBasisPoints:x.annualRateBasisPoints}));}
export function creditSummary(e:SimulationEngine,companyId:string){return e.finance.snapshot().creditFacilities.filter((x)=>x.companyId===companyId).map((x)=>({id:x.id,status:x.status,limitMinor:x.limitMinor,drawnMinor:x.drawnMinor,headroomMinor:x.limitMinor-x.drawnMinor,accruedInterestMinor:x.accruedInterestMinor}));}
export function cashForecast(e:SimulationEngine,companyId:string,horizonSeconds:number){const end=e.clock.currentGameTime+horizonSeconds,s=e.finance.snapshot();return{projectedPaymentsMinor:s.payables.filter((x)=>x.companyId===companyId&&x.dueTimestamp<=end&&x.status!=="PAID"&&x.status!=="CANCELLED").reduce((n,x)=>n+x.principalMinor-x.amountPaidMinor,0),projectedReceiptsMinor:s.receivables.filter((x)=>x.companyId===companyId&&x.dueTimestamp<=end&&x.status!=="PAID").reduce((n,x)=>n+x.principalMinor-x.amountPaidMinor,0)};}
export function solvencyWarning(e:SimulationEngine,companyId:string){const company=e.finance.company(companyId);if(!company)throw new Error("Company not found");const header=financeHeader(e,companyId),forecast=cashForecast(e,companyId,30*86400),loans=loanSummary(e,companyId),credits=creditSummary(e,companyId);const loanPrincipalMinor=loans.reduce((n,x)=>n+x.principalMinor,0),creditDrawnMinor=credits.reduce((n,x)=>n+x.drawnMinor,0),creditHeadroomMinor=credits.filter((x)=>x.status==="AVAILABLE"||x.status==="ACTIVE").reduce((n,x)=>n+x.headroomMinor,0),accruedInterestMinor=loans.reduce((n,x)=>n+x.accruedInterestMinor,0)+credits.reduce((n,x)=>n+x.accruedInterestMinor,0);return{solvencyStatus:company.solvencyStatus,liquidityWarning:forecast.projectedPaymentsMinor>header.freeCashMinor+creditHeadroomMinor,netDebtMinor:loanPrincipalMinor+creditDrawnMinor-header.cashBalanceMinor,loanPrincipalMinor,creditDrawnMinor,creditHeadroomMinor,accruedInterestMinor,...forecast};}