import { createHash } from "node:crypto";
import { canonicalJson } from "../config/canonical.js";
import { CORE_VERSION, SAVE_SCHEMA_VERSION, type SimulationSpeed } from "../core/constants.js";
import { SimulationEngine } from "../core/engine.js";
import type { CommandEnvelope } from "../core/commands.js";
import type { DomainEvent } from "../core/events.js";
import type { EntityCounterState } from "../core/ids.js";
import type { RngRegistryState } from "../core/rng.js";
import { migrateSave } from "./migrations.js";
import { validateSnapshot, type CoreSnapshot } from "./snapshot.js";
export interface SaveEnvelope{saveSchemaVersion:number;coreVersion:string;configurationBundleVersion:string;configurationHash:string;scenarioId:string;seed:string;currentGameTime:number;paused:boolean;selectedSpeed:SimulationSpeed;entityCounterState:EntityCounterState;rngStreamStates:RngRegistryState;eventInsertionCounter:number;snapshotSequence:number;snapshot:CoreSnapshot;eventsAfterSnapshot:DomainEvent[];commandHistory?:CommandEnvelope[];playerPreferences:Record<string,unknown>;authoritativeStateChecksum:string;migrationHistory?:Array<{fromVersion:number;toVersion:number}>;saveChecksum:string;}
export function calculateSaveChecksum(save:Omit<SaveEnvelope,"saveChecksum">){return createHash("sha256").update(canonicalJson(save),"utf8").digest("hex");}
export function createSave(engine:SimulationEngine,snapshot:CoreSnapshot,includeCommandHistory=true):SaveEnvelope{validateSnapshot(snapshot);if(snapshot.eventLogIndex>engine.eventLog.length)throw new Error("Snapshot event index exceeds event log");engine.checkInvariants();const state=engine.authoritativeState();const bare:Omit<SaveEnvelope,"saveChecksum">={saveSchemaVersion:SAVE_SCHEMA_VERSION,coreVersion:CORE_VERSION,configurationBundleVersion:engine.configurationBundleVersion,configurationHash:engine.configurationHash,scenarioId:engine.scenarioId,seed:engine.seed,currentGameTime:engine.clock.currentGameTime,paused:engine.clock.paused,selectedSpeed:engine.clock.speed,entityCounterState:state.entityCounters,rngStreamStates:state.rngStreams,eventInsertionCounter:state.eventInsertionCounter,snapshotSequence:engine.snapshotSequence,snapshot:structuredClone(snapshot),eventsAfterSnapshot:engine.eventLog.all().slice(snapshot.eventLogIndex),...(includeCommandHistory?{commandHistory:engine.commandHistory.map((c)=>structuredClone(c))}:{}),playerPreferences:{},authoritativeStateChecksum:engine.stateChecksum()};return{...bare,saveChecksum:calculateSaveChecksum(bare)};}
function assertSaveShape(value:Record<string,unknown>):void{for(const key of ["saveSchemaVersion","coreVersion","configurationBundleVersion","configurationHash","scenarioId","seed","currentGameTime","paused","selectedSpeed","entityCounterState","rngStreamStates","eventInsertionCounter","snapshotSequence","snapshot","eventsAfterSnapshot","playerPreferences","authoritativeStateChecksum","saveChecksum"])if(!(key in value))throw new Error(`Save field missing: ${key}`);}
function migratedAndVerified(raw:unknown):SaveEnvelope{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("Save must be an object");const original=structuredClone(raw as Record<string,unknown>),originalVersion=original.saveSchemaVersion;if(Number(originalVersion)<SAVE_SCHEMA_VERSION){const stored=original.saveChecksum;if(typeof stored!=="string")throw new Error("Old save checksum is missing");const{saveChecksum:_,...oldBare}=original;if(createHash("sha256").update(canonicalJson(oldBare),"utf8").digest("hex")!==stored)throw new Error("Old save checksum mismatch");}const migrated=migrateSave(original);if(Number(originalVersion)<SAVE_SCHEMA_VERSION){assertSaveShape(migrated);const candidate=migrated as unknown as SaveEnvelope;candidate.authoritativeStateChecksum=replayEventsFromSnapshot(candidate).stateChecksum();const{saveChecksum:_,...migratedBare}=candidate;candidate.saveChecksum=calculateSaveChecksum(migratedBare);}assertSaveShape(migrated);const save=migrated as unknown as SaveEnvelope;if(save.saveSchemaVersion!==SAVE_SCHEMA_VERSION)throw new Error(`Unsupported save schema version: ${save.saveSchemaVersion}`);const{saveChecksum:stored,...bare}=save;if(calculateSaveChecksum(bare)!==stored)throw new Error("Save checksum mismatch");return save;}
export function replayEventsFromSnapshot(save:SaveEnvelope):SimulationEngine{validateSnapshot(save.snapshot);const replay=new SimulationEngine({seed:save.seed,configurationBundleVersion:save.configurationBundleVersion,configurationHash:save.configurationHash,scenarioId:save.scenarioId,clock:save.snapshot.state.clock,entityCounters:save.snapshot.state.entityCounters,rngStreams:save.snapshot.state.rngStreams,scheduledEvents:save.snapshot.state.scheduledEvents,eventInsertionCounter:save.snapshot.state.eventInsertionCounter,finance:save.snapshot.state.finance,routing:save.snapshot.state.routing,inventory:save.snapshot.state.inventory,buyers:save.snapshot.state.buyers,suppliers:save.snapshot.state.suppliers,transport:save.snapshot.state.transport,auctions:save.snapshot.state.auctions,forests:save.snapshot.state.forests,operations:save.snapshot.state.operations,contracts:save.snapshot.state.contracts,exports:save.snapshot.state.exports,markets:save.snapshot.state.markets});for(const event of save.eventsAfterSnapshot)replay.applyReplayEvent(event);replay.checkInvariants();return replay;}
export function loadSave(raw:unknown):SimulationEngine{const save=migratedAndVerified(raw),replay=replayEventsFromSnapshot(save);if(replay.clock.currentGameTime!==save.currentGameTime)throw new Error("Replay game-time mismatch");if(canonicalJson(replay.ids.snapshot())!==canonicalJson(save.entityCounterState))throw new Error("Replay entity-counter mismatch");if(replay.eventInsertionCounter!==save.eventInsertionCounter)throw new Error("Replay insertion-counter mismatch");if(canonicalJson(replay.rng.snapshot())!==canonicalJson(save.rngStreamStates))throw new Error("Replay RNG-state mismatch");if(replay.clock.paused!==save.paused||replay.clock.speed!==save.selectedSpeed)throw new Error("Replay clock-state mismatch");if(replay.stateChecksum()!==save.authoritativeStateChecksum)throw new Error("Replay state-checksum mismatch");replay.restoreNonAuthoritativePersistence(save.snapshotSequence,save.commandHistory??[]);return replay;}
export function serializeSave(save:SaveEnvelope){return`${JSON.stringify(save,null,2)}\n`;}export function parseSave(text:string):SaveEnvelope{return JSON.parse(text) as SaveEnvelope;}