import { createHash } from "node:crypto";import { canonicalJson } from "../config/canonical.js";import { EVENT_SCHEMA_VERSION } from "./constants.js";import { SimulationPhase } from "./phases.js";
export type EventVisibility="PUBLIC"|"PLAYER_PRIVATE"|"ACTOR_PRIVATE"|"DEBUG_ONLY";
export interface ScheduledEvent{eventId:string;eventType:string;scheduledGameTime:number;phase:SimulationPhase;actorId?:string|undefined;targetIds:string[];parentCauseId?:string|undefined;schemaVersion:number;visibility:EventVisibility;payload:Record<string,unknown>;insertionSequence:number;}
export interface DomainEvent{eventId:string;eventType:string;gameTime:number;phase:SimulationPhase;actorId?:string|undefined;targetIds:string[];parentCauseId?:string|undefined;schemaVersion:number;visibility:EventVisibility;payload:Record<string,unknown>;insertionSequence:number;eventHash:string;}
function party(e:{actorId?:string|undefined;targetIds:string[]}){return`${e.actorId??""}\0${[...e.targetIds].sort().join("\0")}`;}function boundaryRank(e:{eventType:string}){return e.eventType==="ClockAdvanced"?-1:0;}
export function compareDomainEvents(a:DomainEvent,b:DomainEvent){return a.gameTime-b.gameTime||boundaryRank(a)-boundaryRank(b);}
function compareScheduled(a:ScheduledEvent,b:ScheduledEvent){return a.scheduledGameTime-b.scheduledGameTime||a.phase-b.phase||party(a).localeCompare(party(b))||a.insertionSequence-b.insertionSequence||a.eventId.localeCompare(b.eventId);}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"){Object.freeze(value);for(const child of Object.values(value as Record<string,unknown>))deepFreeze(child);}return value;}
export class ScheduledEventQueue{private items:ScheduledEvent[]=[];schedule(event:ScheduledEvent){if(!Number.isSafeInteger(event.scheduledGameTime)||event.scheduledGameTime<0)throw new Error("Invalid scheduled game time");this.items.push(structuredClone(event));this.items.sort(compareScheduled);}nextTimestamp(fromInclusive:number,toInclusive:number):number|undefined{return this.items.find((e)=>e.scheduledGameTime>=fromInclusive&&e.scheduledGameTime<=toInclusive)?.scheduledGameTime;}dueAt(time:number,phase:SimulationPhase){const due=this.items.filter((e)=>e.scheduledGameTime===time&&e.phase===phase);this.items=this.items.filter((e)=>!(e.scheduledGameTime===time&&e.phase===phase));return due.map((e)=>structuredClone(e));}consumeForReplay(eventId:string){this.items=this.items.filter((e)=>e.eventId!==eventId);}snapshot(){return this.items.map((e)=>structuredClone(e));}restore(events:ScheduledEvent[]){this.items=events.map((e)=>structuredClone(e));this.items.sort(compareScheduled);}get size(){return this.items.length;}}
export function hashEvent(event:Omit<DomainEvent,"eventHash">){return createHash("sha256").update(canonicalJson(event),"utf8").digest("hex");}
export function createDomainEvent(input:Omit<DomainEvent,"eventHash"|"schemaVersion">&{schemaVersion?:number}):DomainEvent{const unhashed={...input,schemaVersion:input.schemaVersion??EVENT_SCHEMA_VERSION};return deepFreeze({...structuredClone(unhashed),eventHash:hashEvent(unhashed)});}
export class DomainEventLog{private events:DomainEvent[]=[];append(event:DomainEvent){const{eventHash,...bare}=event;if(hashEvent(bare)!==eventHash)throw new Error(`Event checksum mismatch at ${event.eventId}`);this.events.push(deepFreeze(structuredClone(event)));}all():readonly DomainEvent[]{return this.events.map((e)=>structuredClone(e));}restore(events:DomainEvent[]){this.events=[];for(const event of events)this.append(event);}get length(){return this.events.length;}}