import type{CommandEnvelope,CommandResult}from'../core/commands.js';import type{ScheduledEvent}from'../core/events.js';import type{SimulationEngine}from'../core/engine.js';import{SimulationPhase}from'../core/phases.js';import type{Batch,Certainty,CostLayer,Freshness,RecoveryVolumeEntry}from'./types.js';import{allocateInteger,validateComposition,volume,weightedComposition}from'./value-objects.js';import{isValidSortingBand}from'./types.js';
const reject=(c:CommandEnvelope,code:string,message:string):CommandResult=>({accepted:false,commandId:c.commandId,code,message});const activeBatch=(b?:Batch)=>!!b&&!['SPLIT','MERGED','DEPLETED','CANCELLED','CLOSED'].includes(b.status);const fresh=new Set<Freshness>(['FRESH','AGING','DEGRADED']),certain=new Set<Certainty>(['UNKNOWN','SELLER_CLAIMED','ESTIMATED','INSPECTED','SORTED','MEASURED']);
function accepted(e:SimulationEngine,c:CommandEnvelope,eventType:string,payload:Record<string,unknown>,phase=SimulationPhase.PHYSICAL_STATE){const i=e.reserveEventIdentity(),x=e.emitReservedEvent(i,{eventType,phase,actorId:c.actorId,targetIds:[],parentCauseId:c.commandId,visibility:'PLAYER_PRIVATE',payload});return{accepted:true as const,commandId:c.commandId,emittedEventIds:[x.eventId]}}
function validFinance(e:SimulationEngine,id:string){return!!(e.finance.commitment(id)||e.finance.payable(id)||e.finance.receivable(id)||e.finance.snapshot().transactions.find(x=>x.id===id))}
function available(e:SimulationEngine,b:Batch){return b.currentVolumeMilliM3-b.reservedVolumeMilliM3-b.allocatedVolumeMilliM3}
export function registerInventoryCommands(e:SimulationEngine){
 e.registerCommandHandler('CreateDeal',c=>{const p=c.payload;let expected:number;try{expected=volume(p.expectedVolumeMilliM3)}catch{return reject(c,'INVALID_DEAL','Invalid expected volume')}if(!e.finance.company(String(p.companyId))||!String(p.counterpartyId)||p.currency!=='EUR'||!String(p.description)||!Array.isArray(p.financeSourceIds)||p.financeSourceIds.some(x=>!validFinance(e,String(x))))return reject(c,'INVALID_DEAL','Invalid company, finance link, currency, or description');const id=e.ids.next('deal','DEAL'),deal={id,schemaVersion:1 as const,companyId:String(p.companyId),dealType:'DIAGNOSTIC_ACQUISITION' as const,counterpartyId:String(p.counterpartyId),status:'PROPOSED' as const,createdTimestamp:e.clock.currentGameTime,updatedTimestamp:e.clock.currentGameTime,sourceEventIds:[],financeSourceIds:p.financeSourceIds.map(String),lotIds:[],expectedVolumeMilliM3:expected,recognizedVolumeMilliM3:0,allocatedVolumeMilliM3:0,depletedVolumeMilliM3:0,currency:'EUR' as const,costLayerIds:[],description:String(p.description)};return accepted(e,c,'DealCreated',{deal},SimulationPhase.COMMANDS)});
 e.registerCommandHandler('ActivateDeal',c=>{const d=e.inventory.deal(String(c.payload.dealId));if(!d||d.status!=='PROPOSED')return reject(c,'INVALID_DEAL_TRANSITION','Deal must be proposed');return accepted(e,c,'DealActivated',{dealId:d.id},SimulationPhase.COMMANDS)});
 e.registerCommandHandler('CancelDeal',c=>{const d=e.inventory.deal(String(c.payload.dealId));if(!d||!['PROPOSED','ACTIVE'].includes(d.status)||d.lotIds.length)return reject(c,'INVALID_DEAL_TRANSITION','Only an empty proposed or active deal may be cancelled');return accepted(e,c,'DealCancelled',{dealId:d.id},SimulationPhase.COMMANDS)});
 e.registerCommandHandler('CloseDeal',c=>{const d=e.inventory.deal(String(c.payload.dealId));if(!d||['CANCELLED','CLOSED'].includes(d.status)||!String(c.payload.reason))return reject(c,'INVALID_DEAL_TRANSITION','Deal cannot close');return accepted(e,c,'DealClosed',{dealId:d.id,reason:String(c.payload.reason)},SimulationPhase.COMMANDS)});
 e.registerCommandHandler('CreateLot',c=>{const p=c.payload,d=e.inventory.deal(String(p.dealId)),owner=e.finance.company(String(p.ownerCompanyId)),loc=e.routing.location(String(p.locationId));let original:number,composition;try{original=volume(p.originalVolumeMilliM3);composition=validateComposition(p.composition,original)}catch(x){return reject(c,'INVALID_LOT',String(x))}if(!d||!['ACTIVE','PARTIALLY_FULFILLED','FULFILLED'].includes(d.status)||!owner||!loc||loc.status!=='ACTIVE'||!String(p.custodyActorId)||!fresh.has(p.freshness as Freshness)||!certain.has(p.certainty as Certainty)||original<=0)return reject(c,'INVALID_LOT','Invalid lot references or state');const id=e.ids.next('lot','LOT'),lot={id,schemaVersion:1 as const,dealId:d.id,ownerCompanyId:owner.id,custodyActorId:String(p.custodyActorId),locationId:loc.id,status:'AVAILABLE' as const,createdTimestamp:e.clock.currentGameTime,sourceEventIds:[],originalVolumeMilliM3:original,availableVolumeMilliM3:0,reservedVolumeMilliM3:0,allocatedVolumeMilliM3:0,depletedVolumeMilliM3:0,batchIds:[],composition,freshness:p.freshness as Freshness,certainty:p.certainty as Certainty,costLayerIds:[],rootId:id};return accepted(e,c,'LotCreated',{lot})});
 e.registerCommandHandler('CreateInitialBatch',c=>{const p=c.payload,l=e.inventory.lot(String(p.lotId));let v:number,composition;try{v=volume(p.volumeMilliM3);composition=validateComposition(p.composition,v)}catch(x){return reject(c,'INVALID_BATCH',String(x))}const created=l?e.inventory.snapshot().batches.filter(b=>b.rootLotId===l.id&&!b.parentBatchIds.length).reduce((n,b)=>n+b.originalVolumeMilliM3,0):0;if(!l||v<=0||created+v>l.originalVolumeMilliM3||!e.routing.location(l.locationId))return reject(c,'INVALID_BATCH','Batch exceeds lot or references invalid lot');const id=e.ids.next('batch','BATCH'),batch:Batch={id,schemaVersion:1,rootLotId:l.id,parentBatchIds:[],childBatchIds:[],ownerCompanyId:l.ownerCompanyId,custodyActorId:l.custodyActorId,locationId:l.locationId,status:'AVAILABLE',createdTimestamp:e.clock.currentGameTime,sourceEventIds:[],originalVolumeMilliM3:v,currentVolumeMilliM3:v,reservedVolumeMilliM3:0,allocatedVolumeMilliM3:0,depletedVolumeMilliM3:0,composition,freshness:l.freshness,certainty:l.certainty,costLayerIds:[],ancestryDepth:0,historyEventIds:[]};return accepted(e,c,'BatchCreated',{batch})});
 e.registerCommandHandler('CreateInventoryReservation',c=>{const p=c.payload,b=e.inventory.batch(String(p.batchId));let v:number;try{v=volume(p.volumeMilliM3)}catch{return reject(c,'INVALID_RESERVATION','Invalid volume')}const expiry=p.expectedReleaseTimestamp;if(!b||!activeBatch(b)||v<=0||v>available(e,b)||b.ownerCompanyId!==String(p.companyId)||!String(p.purpose)||!String(p.sourceObjectId)||expiry!==undefined&&(!Number.isSafeInteger(expiry)||Number(expiry)<e.clock.currentGameTime))return reject(c,'INVALID_RESERVATION','Reservation unavailable or invalid');const id=e.ids.next('reservation','RESERVATION'),scheduledEvents:ScheduledEvent[]=[];if(expiry!==undefined){const si=e.reserveEventIdentity();scheduledEvents.push({eventId:si.eventId,eventType:'InventoryReservationExpired',scheduledGameTime:Number(expiry),phase:SimulationPhase.JOB_PROGRESS,actorId:c.actorId,targetIds:[id],parentCauseId:c.commandId,schemaVersion:1,visibility:'PLAYER_PRIVATE',payload:{reservationId:id},insertionSequence:si.insertionSequence})}const reservation={id,companyId:String(p.companyId),batchId:b.id,purpose:String(p.purpose),sourceObjectId:String(p.sourceObjectId),volumeMilliM3:v,createdTimestamp:e.clock.currentGameTime,...(expiry!==undefined?{expectedReleaseTimestamp:Number(expiry)}:{}),status:'ACTIVE' as const,sourceEventIds:[]};return accepted(e,c,'InventoryReservationCreated',{reservation,scheduledEvents})});
 for(const [name,eventType]of[['ReleaseInventoryReservation','InventoryReservationReleased'],['ExpireInventoryReservation','InventoryReservationExpired']]as const)e.registerCommandHandler(name,c=>{const r=e.inventory.reservation(String(c.payload.reservationId));if(!r||r.status!=='ACTIVE')return reject(c,'INVALID_RESERVATION_TRANSITION','Reservation is not active');return accepted(e,c,eventType,{reservationId:r.id})});
 e.registerCommandHandler('SplitBatch',c=>{const p=c.payload,b=e.inventory.batch(String(p.batchId));if(!b||!activeBatch(b)||b.reservedVolumeMilliM3||b.allocatedVolumeMilliM3)return reject(c,'INVALID_SPLIT','Batch is not splittable');let volumes:number[];try{if(!Array.isArray(p.childVolumesMilliM3))throw 0;volumes=p.childVolumesMilliM3.map(x=>volume(x));}catch{return reject(c,'INVALID_SPLIT','Invalid child volumes')}if(volumes.length<2||volumes.some(x=>x<=0)||volumes.reduce((n,x)=>n+x,0)!==b.currentVolumeMilliM3)return reject(c,'INVALID_SPLIT','Full explicit split must conserve volume');const activeLayers=e.inventory.snapshot().costLayers.filter(x=>x.attachedToType==='BATCH'&&x.attachedToId===b.id&&x.status==='ACTIVE'),childIds=volumes.map(()=>e.ids.next('batch','BATCH')),children=volumes.map((v,i):Batch=>({...structuredClone(b),id:childIds[i]!,parentBatchIds:[b.id],childBatchIds:[],status:'AVAILABLE',createdTimestamp:e.clock.currentGameTime,sourceEventIds:[],originalVolumeMilliM3:v,currentVolumeMilliM3:v,reservedVolumeMilliM3:0,allocatedVolumeMilliM3:0,depletedVolumeMilliM3:0,costLayerIds:[],ancestryDepth:b.ancestryDepth+1,historyEventIds:[]}));const childCostLayers:CostLayer[]=[];for(const layer of activeLayers){const amounts=allocateInteger(layer.totalMinor,volumes),attr=allocateInteger(layer.attributableVolumeMilliM3,volumes);for(let i=0;i<children.length;i++)childCostLayers.push({...layer,id:e.ids.next('cost_layer','COST'),attachedToId:children[i]!.id,totalMinor:amounts[i]!,attributableVolumeMilliM3:attr[i]!,createdTimestamp:e.clock.currentGameTime,parentCostLayerId:layer.id,status:'ACTIVE'})}return accepted(e,c,'BatchSplit',{parentBatchId:b.id,children,childCostLayers})});
 e.registerCommandHandler('MergeBatches',c=>{const ids=Array.isArray(c.payload.batchIds)?c.payload.batchIds.map(String):[],bs=ids.map(id=>e.inventory.batch(id));if(ids.length<2||new Set(ids).size!==ids.length||bs.some(x=>!x||!activeBatch(x)))return reject(c,'INVALID_MERGE','Invalid merge sources');const batches=bs as Batch[],first=batches[0]!;if(batches.some(b=>b.ownerCompanyId!==first.ownerCompanyId||b.custodyActorId!==first.custodyActorId||b.locationId!==first.locationId||b.reservedVolumeMilliM3||b.allocatedVolumeMilliM3||b.rootLotId!==first.rootLotId))return reject(c,'INCOMPATIBLE_MERGE','Owner, custody, location, lot, or lifecycle incompatible');const total=batches.reduce((n,b)=>n+b.currentVolumeMilliM3,0),id=e.ids.next('batch','BATCH'),mergedBatch:Batch={...structuredClone(first),id,parentBatchIds:ids,childBatchIds:[],status:'AVAILABLE',createdTimestamp:e.clock.currentGameTime,sourceEventIds:[],originalVolumeMilliM3:total,currentVolumeMilliM3:total,reservedVolumeMilliM3:0,allocatedVolumeMilliM3:0,depletedVolumeMilliM3:0,composition:weightedComposition(batches.map(b=>({volume:b.currentVolumeMilliM3,composition:b.composition}))),costLayerIds:[],ancestryDepth:Math.max(...batches.map(b=>b.ancestryDepth))+1,historyEventIds:[]};const layers=e.inventory.snapshot().costLayers.filter(x=>x.attachedToType==='BATCH'&&ids.includes(x.attachedToId)&&x.status==='ACTIVE'),mergedCostLayers=layers.map(layer=>({...layer,id:e.ids.next('cost_layer','COST'),attachedToId:id,parentCostLayerId:layer.id,category:'INHERITED' as const,createdTimestamp:e.clock.currentGameTime,status:'ACTIVE' as const}));return accepted(e,c,'BatchesMerged',{sourceBatchIds:ids,mergedBatch,mergedCostLayers})});
 e.registerCommandHandler('CreateLoad',c=>{const p=c.payload,owner=e.finance.company(String(p.ownerCompanyId)),loc=e.routing.location(String(p.originLocationId)),dest=p.destinationLocationId===undefined?undefined:e.routing.location(String(p.destinationLocationId));if(!owner||!loc||loc.status!=='ACTIVE'||dest&&dest.status!=='ACTIVE'||!String(p.custodyActorId))return reject(c,'INVALID_LOAD','Invalid load references');const id=e.ids.next('load','LOAD'),load={id,schemaVersion:1 as const,ownerCompanyId:owner.id,custodyActorId:String(p.custodyActorId),originLocationId:loc.id,currentLocationId:loc.id,...(dest?{destinationLocationId:dest.id}:{}),routeEdgeIds:[],status:'PLANNED' as const,createdTimestamp:e.clock.currentGameTime,sourceEventIds:[],allocationIds:[],totalAllocatedVolumeMilliM3:0,movedVolumeMilliM3:0,unloadedVolumeMilliM3:0,depletedVolumeMilliM3:0,costLayerIds:[]};return accepted(e,c,'LoadCreated',{load})});
 e.registerCommandHandler('AllocateBatchToLoad',c=>{const p=c.payload,b=e.inventory.batch(String(p.batchId)),l=e.inventory.load(String(p.loadId));let v:number;try{v=volume(p.volumeMilliM3)}catch{return reject(c,'INVALID_ALLOCATION','Invalid volume')}const r=p.reservationId===undefined?undefined:e.inventory.reservation(String(p.reservationId)),capacity=r?.status==='ACTIVE'&&r.batchId===b?.id?r.volumeMilliM3:b?available(e,b):0;if(!b||!l||!activeBatch(b)||!['PLANNED','ALLOCATED'].includes(l.status)||v<=0||v>capacity||b.ownerCompanyId!==l.ownerCompanyId||b.custodyActorId!==l.custodyActorId||b.locationId!==l.currentLocationId||r&&v!==r.volumeMilliM3)return reject(c,'INVALID_ALLOCATION','Allocation unavailable or incompatible');const id=e.ids.next('allocation','ALLOCATION'),allocation={id,batchId:b.id,loadId:l.id,volumeMilliM3:v,...(r?{reservationId:r.id}:{}),status:'ACTIVE' as const,createdTimestamp:e.clock.currentGameTime,sourceEventIds:[]};return accepted(e,c,'BatchAllocatedToLoad',{allocation})});
 for(const [name,eventType,status]of[['ReleaseLoadAllocation','LoadAllocationReleased','ACTIVE'],['FinalizeLoadAllocation','LoadAllocationFinalized','ACTIVE']]as const)e.registerCommandHandler(name,c=>{const a=e.inventory.allocation(String(c.payload.allocationId));if(!a||a.status!==status)return reject(c,'INVALID_ALLOCATION_TRANSITION','Allocation is not active');return accepted(e,c,eventType,{allocationId:a.id})});
 for(const type of ['MoveBatch','MoveLoad']as const)e.registerCommandHandler(type,c=>{const isBatch=type==='MoveBatch',x=isBatch?e.inventory.batch(String(c.payload.batchId)):e.inventory.load(String(c.payload.loadId)),from=(x as any)?.locationId??(x as any)?.currentLocationId,to=String(c.payload.toLocationId);if(!x||!e.routing.location(to)||from===to)return reject(c,'INVALID_MOVE','Invalid movement endpoints');let quote;try{quote=e.routing.route(from,to)}catch{return reject(c,'NO_ROUTE','No active route exists')}return accepted(e,c,isBatch?'BatchMoved':'LoadMoved',{[isBatch?'batchId':'loadId']:x.id,fromLocationId:from,toLocationId:to,routeEdgeIds:quote.edgeIds,distanceMetres:quote.distanceMetres,travelSeconds:quote.travelSeconds})});
 e.registerCommandHandler('UnloadLoad',c=>{const l=e.inventory.load(String(c.payload.loadId));if(!l||!['ALLOCATED','READY','MOVED'].includes(l.status)||!l.totalAllocatedVolumeMilliM3)return reject(c,'INVALID_UNLOAD','Load cannot unload');return accepted(e,c,'LoadUnloaded',{loadId:l.id})});
 e.registerCommandHandler('DepleteBatch',c=>{const b=e.inventory.batch(String(c.payload.batchId));let v:number;try{v=volume(c.payload.volumeMilliM3)}catch{return reject(c,'INVALID_DEPLETION','Invalid volume')}if(!b||!activeBatch(b)||v<=0||v>available(e,b))return reject(c,'INVALID_DEPLETION','Insufficient available batch volume');return accepted(e,c,'BatchDepleted',{batchId:b.id,volumeMilliM3:v})});
 e.registerCommandHandler('DepleteLoad',c=>{const l=e.inventory.load(String(c.payload.loadId));let v:number;try{v=volume(c.payload.volumeMilliM3)}catch{return reject(c,'INVALID_DEPLETION','Invalid volume')}if(!l||!['UNLOADED','MOVED','ALLOCATED'].includes(l.status)||v<=0||v>l.totalAllocatedVolumeMilliM3-l.depletedVolumeMilliM3)return reject(c,'INVALID_DEPLETION','Insufficient load volume');return accepted(e,c,'LoadDepleted',{loadId:l.id,volumeMilliM3:v})});
 for(const [name,eventType,key]of[['TransferOwnership','OwnershipTransferred','ownerCompanyId'],['TransferCustody','CustodyTransferred','custodyActorId']]as const)e.registerCommandHandler(name,c=>{const type=String(c.payload.objectType),id=String(c.payload.objectId),x=type==='BATCH'?e.inventory.batch(id):type==='LOAD'?e.inventory.load(id):undefined,value=String(c.payload[key]);if(!x||!value||key==='ownerCompanyId'&&!e.finance.company(value))return reject(c,'INVALID_TRANSFER','Invalid transfer');return accepted(e,c,eventType,{objectType:type,objectId:id,[key]:value})});
 e.registerCommandHandler('SetBatchRecoveryVolumes',c=>{const p=c.payload,b=e.inventory.batch(String(p.batchId));if(!b||['SPLIT','MERGED','DEPLETED','CANCELLED','CLOSED'].includes(b.status))return reject(c,'INVALID_BATCH','Batch not available');// B5: reject if batch has active queued sort job or already sorted
  if (b.certainty === 'SORTED' || b.certainty === 'MEASURED' || b.certainty === 'HIGH')
    return reject(c, 'BATCH_LOCKED', 'Batch recovery locked after sorting or measurement');
  const volumes: RecoveryVolumeEntry[]=Array.isArray(p.volumes)?p.volumes.map((v:any)=>({label:String(v.label) as any,volumeMilliM3:Number(v.volumeMilliM3)})):[];if(!volumes.length||volumes.some((v:RecoveryVolumeEntry)=>!v.label||!isValidSortingBand(v.label)||!Number.isSafeInteger(v.volumeMilliM3)||v.volumeMilliM3<=0))return reject(c,'INVALID_VOLUMES','Each recovery entry needs a valid sorting-band label and positive volume');
  // Reject if batch has an active queued sorting job
  const ops = (e as any).operations;
  if (ops && ops.snapshot().sortJobs.some((sj: any) => sj.batchId === b.id && sj.status === 'QUEUED'))
    return reject(c, 'BATCH_LOCKED', 'Batch has an active queued sorting job');
  // Duplicate label check
  const labels = volumes.map((v: RecoveryVolumeEntry) => v.label);
  if (new Set(labels).size !== labels.length) return reject(c, 'DUPLICATE_LABELS', 'Duplicate recovery-band labels');
  const total=volumes.reduce((n:number,v:RecoveryVolumeEntry)=>n+v.volumeMilliM3,0);const available=b.currentVolumeMilliM3-b.reservedVolumeMilliM3-b.allocatedVolumeMilliM3;if(total>available)return reject(c,'RECOVERY_EXCEEDS_AVAILABLE','Recovery total exceeds available batch volume');return accepted(e,c,'BatchRecoveryVolumesSet',{batchId:b.id,volumes})});
 e.registerCommandHandler('AddCostLayer',c=>{const p=c.payload,type=String(p.attachedToType),id=String(p.attachedToId),target=type==='DEAL'?e.inventory.deal(id):type==='LOT'?e.inventory.lot(id):type==='BATCH'?e.inventory.batch(id):type==='LOAD'?e.inventory.load(id):undefined;let amount:number,attr:number;try{amount=volume(p.totalMinor,'cost');attr=volume(p.attributableVolumeMilliM3)}catch{return reject(c,'INVALID_COST_LAYER','Invalid integer values')}const financeId=p.financeSourceId===undefined?undefined:String(p.financeSourceId),categories=['ACQUISITION','OPERATIONAL','HANDLING','TRANSPORT_PLACEHOLDER','FINANCING_ATTRIBUTION','ADJUSTMENT','INHERITED'];if(!target||p.currency!=='EUR'||!categories.includes(String(p.category))||financeId&&!validFinance(e,financeId)||!String(p.sourceObjectId)||!String(p.provenanceReference))return reject(c,'INVALID_COST_LAYER','Invalid target, finance link, or category');const layer:CostLayer={id:e.ids.next('cost_layer','COST'),attachedToType:type as any,attachedToId:id,sourceObjectId:String(p.sourceObjectId),category:p.category as any,currency:'EUR',totalMinor:amount,attributableVolumeMilliM3:attr,allocationMethod:p.allocationMethod==='VOLUME_PROPORTIONAL'?'VOLUME_PROPORTIONAL':'DIRECT',createdTimestamp:e.clock.currentGameTime,...(financeId?{financeSourceId:financeId}:{}),provenanceReference:String(p.provenanceReference),status:'ACTIVE'};return accepted(e,c,'CostLayerAdded',{costLayer:layer})});
}
