export const COMPOSITION_SCALE=10_000;
export type CurrencyCode='EUR';
export interface Share{id:string;basisPoints:number}
export interface Composition{species:Share[];assortment:Share[];quality:Share[]}
export type Freshness='FRESH'|'AGING'|'DEGRADED';
export type Certainty='UNKNOWN'|'SELLER_CLAIMED'|'ESTIMATED'|'INSPECTED'|'SORTED'|'MEASURED'|'HIGH';
export type SortingBand='A'|'B_PLUS'|'B'|'B_WEAK'|'C'|'TARA_14_18'|'PULP_REJECT'|'BRAKIS'|'LOSS';
export const SORTING_BANDS:readonly string[]=['A','B_PLUS','B','B_WEAK','C','TARA_14_18','PULP_REJECT','BRAKIS','LOSS'];
export function isValidSortingBand(label:string):label is SortingBand{return SORTING_BANDS.includes(label);}
export interface RecoveryVolumeEntry{label:SortingBand;volumeMilliM3:number}
export interface CostLayer{id:string;attachedToType:'DEAL'|'LOT'|'BATCH'|'LOAD';attachedToId:string;sourceObjectId:string;category:'ACQUISITION'|'OPERATIONAL'|'HANDLING'|'TRANSPORT_PLACEHOLDER'|'FINANCING_ATTRIBUTION'|'ADJUSTMENT'|'INHERITED';currency:CurrencyCode;totalMinor:number;attributableVolumeMilliM3:number;allocationMethod:'DIRECT'|'VOLUME_PROPORTIONAL';createdTimestamp:number;parentCostLayerId?:string;financeSourceId?:string;provenanceReference:string;status:'ACTIVE'|'ALLOCATED'}
export interface Deal{id:string;schemaVersion:1;companyId:string;dealType:'DIAGNOSTIC_ACQUISITION';counterpartyId:string;status:'PROPOSED'|'ACTIVE'|'PARTIALLY_FULFILLED'|'FULFILLED'|'CANCELLED'|'CLOSED';createdTimestamp:number;updatedTimestamp:number;sourceEventIds:string[];financeSourceIds:string[];lotIds:string[];expectedVolumeMilliM3:number;recognizedVolumeMilliM3:number;allocatedVolumeMilliM3:number;depletedVolumeMilliM3:number;currency:CurrencyCode;costLayerIds:string[];description:string;closureReason?:string}
export interface Lot{id:string;schemaVersion:1;dealId:string;ownerCompanyId:string;custodyActorId:string;locationId:string;status:'AVAILABLE'|'PARTIALLY_ALLOCATED'|'FULLY_ALLOCATED'|'DEPLETED'|'CANCELLED'|'CLOSED';createdTimestamp:number;sourceEventIds:string[];originalVolumeMilliM3:number;availableVolumeMilliM3:number;reservedVolumeMilliM3:number;allocatedVolumeMilliM3:number;depletedVolumeMilliM3:number;batchIds:string[];composition:Composition;freshness:Freshness;certainty:Certainty;costLayerIds:string[];rootId:string}
export interface Batch{id:string;schemaVersion:1;rootLotId:string;parentBatchIds:string[];childBatchIds:string[];ownerCompanyId:string;custodyActorId:string;locationId:string;status:'AVAILABLE'|'PARTIALLY_RESERVED'|'FULLY_RESERVED'|'PARTIALLY_LOADED'|'FULLY_LOADED'|'DEPLETED'|'SPLIT'|'MERGED'|'CANCELLED'|'CLOSED';createdTimestamp:number;sourceEventIds:string[];originalVolumeMilliM3:number;currentVolumeMilliM3:number;reservedVolumeMilliM3:number;allocatedVolumeMilliM3:number;depletedVolumeMilliM3:number;composition:Composition;freshness:Freshness;certainty:Certainty;costLayerIds:string[];ancestryDepth:number;historyEventIds:string[];recoveryVolumes?:RecoveryVolumeEntry[];sortingLabel?:Exclude<SortingBand,'LOSS'>}
export interface Allocation{id:string;batchId:string;loadId:string;volumeMilliM3:number;reservationId?:string;status:'ACTIVE'|'FINALIZED'|'RELEASED'|'DEPLETED';createdTimestamp:number;sourceEventIds:string[]}
export interface Load{id:string;schemaVersion:1;ownerCompanyId:string;custodyActorId:string;originLocationId:string;currentLocationId:string;destinationLocationId?:string;routeEdgeIds:string[];status:'PLANNED'|'ALLOCATED'|'READY'|'MOVED'|'UNLOADED'|'CANCELLED'|'DEPLETED'|'CLOSED';createdTimestamp:number;sourceEventIds:string[];allocationIds:string[];totalAllocatedVolumeMilliM3:number;movedVolumeMilliM3:number;unloadedVolumeMilliM3:number;depletedVolumeMilliM3:number;costLayerIds:string[]}
export interface Reservation{id:string;companyId:string;batchId:string;purpose:string;sourceObjectId:string;volumeMilliM3:number;createdTimestamp:number;expectedReleaseTimestamp?:number;status:'ACTIVE'|'CONSUMED'|'RELEASED'|'EXPIRED'|'FAILED';allocationId?:string;sourceEventIds:string[]}
export interface InventorySnapshot{appliedEventIds:string[];deals:Deal[];lots:Lot[];batches:Batch[];loads:Load[];reservations:Reservation[];allocations:Allocation[];costLayers:CostLayer[]}
