import{COMPOSITION_SCALE,type Composition,type Share}from'./types.js';
export function volume(value:unknown,name='volume'){if(!Number.isSafeInteger(value)||Number(value)<0)throw new Error(`${name} must be a nonnegative safe integer thousandths of m³`);return Number(value)}
export function addVolume(a:number,b:number){const x=a+b;if(!Number.isSafeInteger(x))throw new Error('Volume overflow');return x}
export function subtractVolume(a:number,b:number){volume(a);volume(b);if(b>a)throw new Error('Volume underflow');return a-b}
const allowed={species:new Set(['species.birch','species.spruce','species.pine','species.aspen','species.alder','species.oak']),assortment:new Set(['assortment.veneer_logs','assortment.sawlogs','assortment.pulpwood','assortment.energy_wood','assortment.reject']),quality:new Set(['quality.birch.a','quality.birch.b','quality.birch.tara_c','quality.birch.brakis'])};
export function validateComposition(c:unknown,objectVolume:number):Composition{if(!c||typeof c!=='object')throw new Error('Composition is required');const result={} as Composition;for(const key of ['species','assortment','quality']as const){const input=(c as any)[key];if(!Array.isArray(input)||(!input.length&&objectVolume>0))throw new Error(`${key} composition is required`);const seen=new Set<string>();let sum=0;result[key]=input.map((x:any)=>{if(!x||typeof x.id!=='string'||!allowed[key].has(x.id)||seen.has(x.id)||!Number.isSafeInteger(x.basisPoints)||x.basisPoints<=0)throw new Error(`Invalid ${key} composition`);seen.add(x.id);sum+=x.basisPoints;return{id:x.id,basisPoints:x.basisPoints}});if(objectVolume>0&&sum!==COMPOSITION_SCALE)throw new Error(`${key} composition must total ${COMPOSITION_SCALE}`);if(objectVolume===0&&sum!==0)throw new Error('Zero volume composition must be empty');}return result}
function weightedVector(parts:Array<{volume:number;shares:Share[]}>):Share[]{const total=parts.reduce((n,x)=>addVolume(n,x.volume),0),ids=[...new Set(parts.flatMap(x=>x.shares.map(s=>s.id)))];if(total===0)return[];const rows=ids.map(id=>{const numerator=parts.reduce((n,x)=>n+BigInt(x.volume)*BigInt(x.shares.find(s=>s.id===id)?.basisPoints??0),0n),base=numerator/BigInt(total),remainder=numerator%BigInt(total);return{id,basisPoints:Number(base),remainder,index:ids.indexOf(id)}});let missing=COMPOSITION_SCALE-rows.reduce((n,x)=>n+x.basisPoints,0);rows.sort((a,b)=>b.remainder===a.remainder?a.index-b.index:b.remainder>a.remainder?1:-1);for(let i=0;i<missing;i++)rows[i%rows.length]!.basisPoints++;return rows.sort((a,b)=>a.index-b.index).map(({id,basisPoints})=>({id,basisPoints}));}
export function weightedComposition(parts:Array<{volume:number;composition:Composition}>):Composition{return{species:weightedVector(parts.map(x=>({volume:x.volume,shares:x.composition.species}))),assortment:weightedVector(parts.map(x=>({volume:x.volume,shares:x.composition.assortment}))),quality:weightedVector(parts.map(x=>({volume:x.volume,shares:x.composition.quality})))}}
export function allocateInteger(total:number,weights:number[]):number[]{volume(total,'total');if(!weights.length||weights.some(x=>!Number.isSafeInteger(x)||x<=0))throw new Error('Invalid allocation weights');const denominator=weights.reduce(addVolume,0),parts=weights.map((w,i)=>{const n=BigInt(total)*BigInt(w);return{i,value:Number(n/BigInt(denominator)),remainder:n%BigInt(denominator)}}),missing=total-parts.reduce((n,x)=>n+x.value,0);parts.sort((a,b)=>b.remainder===a.remainder?a.i-b.i:b.remainder>a.remainder?1:-1);for(let i=0;i<missing;i++)parts[i]!.value++;return parts.sort((a,b)=>a.i-b.i).map(x=>x.value)}
