import type{Composition}from'../inventory/types.js';
export interface CompatibilityRule{speciesId:string;assortmentId:string;accepted:boolean}
export interface BuyerTruth{measurementBiasMinBasisPoints:number;measurementBiasMaxBasisPoints:number;strictnessBasisPoints:number;fictionalBehaviorNote:string}
export interface Buyer{id:string;schemaVersion:1;configId:string;displayName:string;fictional:true;buyerType:'BIRCH_VENEER'|'CONIFER_SAWMILL'|'PULPWOOD'|'ENERGY';companyId:string;locationId:string;status:'ACTIVE'|'PAUSED'|'CLOSED';compatibility:CompatibilityRule[];capacityMilliM3:number;stockMilliM3:number;targetStockMilliM3:number;consumptionMilliM3PerDay:number;hungerBasisPoints:number;paymentTermsSeconds:number;instantPaymentDiscountMinorPerM3:number;truth:BuyerTruth;createdTimestamp:number;sourceEventIds:string[]}
export interface PriceCardBreakdown{baseRateMinorPerM3:number;hungerAdjustmentMinorPerM3:number;capacityAdjustmentMinorPerM3:number;instantPaymentDiscountMinorPerM3:number;finalRateMinorPerM3:number;hungerBasisPoints:number;capacityUtilizationBasisPoints:number;causeEventIds:string[]}
export interface PriceCard{id:string;buyerId:string;schemaVersion:1;currency:'EUR';speciesId:string;assortmentId:string;paymentOption:'STANDARD'|'INSTANT';createdTimestamp:number;breakdown:PriceCardBreakdown;status:'ACTIVE'|'SUPERSEDED';sourceEventIds:string[]}
export interface GradeAllocation{qualityId:string;volumeMilliM3:number}
export interface MeasurementAct{id:string;buyerId:string;loadId:string;priceCardId:string;gateDecision:'ACCEPT'|'REPRICE'|'REFUSE';dispatchedVolumeMilliM3:number;measuredVolumeMilliM3:number;acceptedVolumeMilliM3:number;rejectedVolumeMilliM3:number;measurementAdjustmentBasisPoints:number;gradeAllocations:GradeAllocation[];composition:Composition;rateMinorPerM3:number;receivableId?:string;principalMinor:number;paymentTimestamp?:number;status:'REFUSED'|'ACCEPTED'|'DISPUTED'|'SETTLED';disputeChoice?:'ACCEPT_RESULT'|'CHALLENGE';reasonCodes:string[];createdTimestamp:number;sourceEventIds:string[]}
export interface BuyerSnapshot{appliedEventIds:string[];buyers:Buyer[];priceCards:PriceCard[];measurements:MeasurementAct[]}
